"use strict";

/*
 * Curated singer dataset used for matching.
 *
 * low/high are approximate, commonly-cited *comfortable* singing ranges (not
 * extreme recorded ranges), which suits matching against a short sung line.
 *
 * voice.*     0–100 curated perceptual ratings (brightness, warmth, weight,
 *             breathiness, roughness, vibrato strength). These are human-style
 *             perceptual estimates, not acoustic measurements, and are compared
 *             only against the user's *derived* perceptual scores.
 * technique   how the singer uses the voice (shared vocabulary with engine.js):
 *             vibrato, straight tone, breathy, rasp, belt, falsetto, runs,
 *             scoops, slides, soft onset, firm onset, vocal fry.
 * delivery    performance style: legato, flowing, conversational, clipped,
 *             sustained, dynamic, understated, controlled, dramatic, rhythmic,
 *             behind-beat, precise, intimate, elastic, restrained, powerful.
 * personality derived descriptor tags, never used for similarity.
 * genres      musical style — kept separate from acoustic similarity.
 */
const SINGERS = [
  {
    id: "freddie-mercury", name: "Freddie Mercury", type: "Tenor",
    lang: "en", low: "F2", high: "F5", tone: "bright", genres: ["Rock", "Pop"],
    blurb: "Queen's frontman — famous for a huge range, raw power and theatrical delivery.",
    songs: ["Somebody to Love", "Don't Stop Me Now", "Love of My Life", "Bohemian Rhapsody", "We Are the Champions"],
    voice: { brightness: 70, warmth: 55, weight: 60, breathiness: 15, roughness: 40, vibrato: 80 },
    technique: ["vibrato", "belt", "rasp", "slides"],
    delivery: ["dramatic", "dynamic", "precise", "sustained"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "adele", name: "Adele", type: "Mezzo-soprano",
    lang: "en", low: "C3", high: "C5", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Rich, emotive mezzo with a warm lower register and powerful belts.",
    songs: ["Someone Like You", "Rolling in the Deep", "Easy on Me", "Hello", "When We Were Young"],
    voice: { brightness: 35, warmth: 70, weight: 70, breathiness: 25, roughness: 30, vibrato: 65 },
    technique: ["belt", "vibrato", "slides"],
    delivery: ["dramatic", "sustained", "dynamic", "legato"],
    personality: ["soulful", "commanding"],
  },
  {
    id: "ed-sheeran", name: "Ed Sheeran", type: "Tenor",
    lang: "en", low: "A2", high: "B4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Soft, breathy tenor built for intimate, melodic pop and acoustic songs.",
    songs: ["Perfect", "Thinking Out Loud", "Photograph", "Shape of You", "Shivers"],
    voice: { brightness: 55, warmth: 60, weight: 35, breathiness: 55, roughness: 15, vibrato: 30 },
    technique: ["breathy", "soft onset", "straight tone", "runs"],
    delivery: ["conversational", "rhythmic", "intimate", "legato"],
    personality: ["intimate", "conversational"],
  },
  {
    id: "beyonce", name: "Beyoncé", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "E5", tone: "bright", genres: ["R&B", "Pop"],
    blurb: "Agile, powerful mezzo with dazzling runs and precise control.",
    songs: ["Halo", "Love on Top", "If I Were a Boy", "Crazy in Love", "Texas Hold 'Em"],
    voice: { brightness: 65, warmth: 60, weight: 70, breathiness: 15, roughness: 20, vibrato: 70 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["precise", "powerful", "dynamic", "rhythmic"],
    personality: ["polished", "commanding"],
  },
  {
    id: "whitney-houston", name: "Whitney Houston", type: "Soprano",
    lang: "en", low: "C3", high: "C6", tone: "bright", genres: ["Pop", "R&B", "Gospel"],
    blurb: "One of the great pop voices — soaring belts and gospel-rooted phrasing.",
    songs: ["I Will Always Love You", "I Wanna Dance with Somebody", "Greatest Love of All", "How Will I Know", "I Have Nothing"],
    voice: { brightness: 70, warmth: 60, weight: 75, breathiness: 10, roughness: 15, vibrato: 85 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["powerful", "dramatic", "sustained", "precise"],
    personality: ["soaring", "polished"],
  },
  {
    id: "sam-smith", name: "Sam Smith", type: "Tenor",
    lang: "en", low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Silky tenor with an effortless falsetto and emotional delivery.",
    songs: ["Stay with Me", "Too Good at Goodbyes", "Lay Me Down", "Unholy", "I'm Not the Only One"],
    voice: { brightness: 55, warmth: 65, weight: 40, breathiness: 40, roughness: 15, vibrato: 70 },
    technique: ["falsetto", "vibrato", "runs", "soft onset"],
    delivery: ["legato", "sustained", "dramatic", "intimate"],
    personality: ["vulnerable", "soulful"],
  },
  {
    id: "ariana-grande", name: "Ariana Grande", type: "Soprano",
    lang: "en", low: "G3", high: "E6", tone: "bright", genres: ["Pop", "R&B"],
    blurb: "Light lyric soprano with a famous whistle register and nimble runs.",
    songs: ["Into You", "No Tears Left to Cry", "POV", "7 rings", "we can't be friends (wait for your love)"],
    voice: { brightness: 75, warmth: 45, weight: 30, breathiness: 35, roughness: 10, vibrato: 60 },
    technique: ["runs", "falsetto", "vibrato", "breathy"],
    delivery: ["precise", "legato", "rhythmic", "controlled"],
    personality: ["crystalline", "polished"],
  },
  {
    id: "bruno-mars", name: "Bruno Mars", type: "Tenor",
    lang: "en", low: "C3", high: "C5", tone: "bright", genres: ["Pop", "Funk", "R&B"],
    blurb: "Versatile retro-flavoured tenor — smooth, punchy and playful.",
    songs: ["When I Was Your Man", "Just the Way You Are", "Grenade", "Die with a Smile", "Leave the Door Open"],
    voice: { brightness: 65, warmth: 60, weight: 50, breathiness: 15, roughness: 25, vibrato: 60 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["rhythmic", "precise", "dynamic", "elastic"],
    personality: ["playful", "polished"],
  },
  {
    id: "frank-sinatra", name: "Frank Sinatra", type: "Baritone",
    lang: "en", low: "G2", high: "G4", tone: "warm", genres: ["Jazz", "Swing"],
    blurb: "The definitive crooner — relaxed phrasing and a velvety baritone.",
    songs: ["Fly Me to the Moon", "My Way", "Come Fly with Me", "The Way You Look Tonight", "New York, New York"],
    voice: { brightness: 45, warmth: 75, weight: 60, breathiness: 15, roughness: 15, vibrato: 55 },
    technique: ["vibrato", "slides", "firm onset"],
    delivery: ["legato", "conversational", "behind-beat", "controlled"],
    personality: ["smooth", "conversational"],
  },
  {
    id: "johnny-cash", name: "Johnny Cash", type: "Bass-baritone",
    lang: "en", low: "E2", high: "E4", tone: "dark", genres: ["Country", "Folk"],
    blurb: "Deep, steady bass-baritone with a storyteller's gravitas.",
    songs: ["Ring of Fire", "I Walk the Line", "Hurt", "Folsom Prison Blues", "A Boy Named Sue"],
    voice: { brightness: 25, warmth: 60, weight: 80, breathiness: 20, roughness: 45, vibrato: 20 },
    technique: ["straight tone", "firm onset", "vocal fry"],
    delivery: ["conversational", "restrained", "controlled"],
    personality: ["earthy", "restrained"],
  },
  {
    id: "barry-white", name: "Barry White", type: "Bass",
    lang: "en", low: "C2", high: "C4", tone: "dark", genres: ["Soul", "R&B", "Disco"],
    blurb: "Legendary low voice — smooth, resonant and unmistakably deep.",
    songs: ["Can't Get Enough of Your Love, Babe", "You're the First, the Last, My Everything", "Never, Never Gonna Give Ya Up", "Let the Music Play", "Practice What You Preach"],
    voice: { brightness: 15, warmth: 85, weight: 95, breathiness: 30, roughness: 30, vibrato: 35 },
    technique: ["straight tone", "soft onset", "vocal fry"],
    delivery: ["intimate", "legato", "sustained", "restrained"],
    personality: ["sensual", "smooth"],
  },
  {
    id: "amy-winehouse", name: "Amy Winehouse", type: "Contralto",
    lang: "en", low: "D3", high: "D5", tone: "dark", genres: ["Soul", "Jazz", "R&B"],
    blurb: "Smoky contralto steeped in jazz — expressive, raw and instantly recognisable.",
    songs: ["Back to Black", "Valerie", "Tears Dry on Their Own", "Rehab", "Love Is a Losing Game"],
    voice: { brightness: 35, warmth: 65, weight: 55, breathiness: 25, roughness: 55, vibrato: 45 },
    technique: ["rasp", "slides", "scoops", "runs"],
    delivery: ["behind-beat", "conversational", "elastic", "dramatic"],
    personality: ["smoky", "raw"],
  },
  {
    id: "tracy-chapman", name: "Tracy Chapman", type: "Contralto",
    lang: "en", low: "F3", high: "C5", tone: "warm", genres: ["Folk", "Rock"],
    blurb: "Warm, grounded contralto with an honest folk storyteller's tone.",
    songs: ["Fast Car", "Give Me One Reason", "Baby Can I Hold You", "Talkin' Bout a Revolution", "The Promise"],
    voice: { brightness: 40, warmth: 75, weight: 60, breathiness: 20, roughness: 25, vibrato: 35 },
    technique: ["straight tone", "firm onset", "slides"],
    delivery: ["conversational", "legato", "restrained", "controlled"],
    personality: ["earthy", "honest"],
  },
  {
    id: "norah-jones", name: "Norah Jones", type: "Contralto",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Jazz", "Pop"],
    blurb: "Hushed, jazzy voice — mellow, intimate and effortlessly smooth.",
    songs: ["Don't Know Why", "Come Away with Me", "Sunrise", "Turn Me On", "Chasing Pirates"],
    voice: { brightness: 40, warmth: 80, weight: 35, breathiness: 55, roughness: 10, vibrato: 30 },
    technique: ["breathy", "soft onset", "straight tone", "slides"],
    delivery: ["intimate", "behind-beat", "legato", "understated"],
    personality: ["dreamy", "intimate"],
  },
  {
    id: "michael-buble", name: "Michael Bublé", type: "Baritone",
    lang: "en", low: "A2", high: "A4", tone: "warm", genres: ["Jazz", "Swing", "Pop"],
    blurb: "Modern crooner — polished baritone with a big-band swagger.",
    songs: ["Feeling Good", "Haven't Met You Yet", "Home", "Everything", "Sway"],
    voice: { brightness: 55, warmth: 70, weight: 55, breathiness: 15, roughness: 15, vibrato: 65 },
    technique: ["vibrato", "belt", "slides"],
    delivery: ["legato", "rhythmic", "dynamic", "precise"],
    personality: ["polished", "playful"],
  },
  {
    id: "elvis-presley", name: "Elvis Presley", type: "Baritone",
    lang: "en", low: "G2", high: "B4", tone: "warm", genres: ["Rock", "Country", "Gospel"],
    blurb: "The King — a rich baritone with rock'n'roll energy and gospel soul.",
    songs: ["Can't Help Falling in Love", "Suspicious Minds", "Jailhouse Rock", "Love Me Tender", "Burning Love"],
    voice: { brightness: 50, warmth: 70, weight: 65, breathiness: 20, roughness: 30, vibrato: 65 },
    technique: ["vibrato", "slides", "scoops", "belt"],
    delivery: ["dramatic", "rhythmic", "elastic", "sustained"],
    personality: ["theatrical", "sensual"],
  },
  {
    id: "david-bowie", name: "David Bowie", type: "Baritone",
    lang: "en", low: "G2", high: "G4", tone: "warm", genres: ["Rock", "Pop"],
    blurb: "Chameleonic baritone — dramatic, characterful and endlessly inventive.",
    songs: ["Heroes", "Life on Mars?", "Space Oddity", "Starman", "Let's Dance"],
    voice: { brightness: 55, warmth: 55, weight: 55, breathiness: 20, roughness: 35, vibrato: 70 },
    technique: ["vibrato", "belt", "slides"],
    delivery: ["dramatic", "elastic", "precise", "sustained"],
    personality: ["theatrical", "inventive"],
  },
  {
    id: "hozier", name: "Hozier", type: "Baritone",
    lang: "en", low: "A2", high: "A4", tone: "dark", genres: ["Rock", "Soul", "Folk"],
    blurb: "Bluesy baritone with gospel weight and a haunting falsetto.",
    songs: ["Take Me to Church", "Cherry Wine", "Work Song", "Too Sweet", "Someone New"],
    voice: { brightness: 35, warmth: 70, weight: 65, breathiness: 30, roughness: 40, vibrato: 55 },
    technique: ["falsetto", "vibrato", "rasp", "belt"],
    delivery: ["dramatic", "sustained", "legato", "dynamic"],
    personality: ["earthy", "soulful"],
  },
  {
    id: "lewis-capaldi", name: "Lewis Capaldi", type: "Tenor",
    lang: "en", low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Gravelly, emotional tenor made for heart-on-sleeve ballads.",
    songs: ["Someone You Loved", "Before You Go", "Bruises", "Wish You the Best", "Hold Me While You Wait"],
    voice: { brightness: 50, warmth: 60, weight: 55, breathiness: 25, roughness: 60, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["dramatic", "sustained", "dynamic", "legato"],
    personality: ["raw", "vulnerable"],
  },
  {
    id: "billie-eilish", name: "Billie Eilish", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "B4", tone: "dark", genres: ["Pop", "Alternative"],
    blurb: "Soft-spoken, breathy mezzo — understated, moody and intimate.",
    songs: ["Ocean Eyes", "Lovely", "What Was I Made For?", "Birds of a Feather", "Happier Than Ever"],
    voice: { brightness: 30, warmth: 55, weight: 20, breathiness: 75, roughness: 10, vibrato: 15 },
    technique: ["breathy", "soft onset", "straight tone", "vocal fry"],
    delivery: ["intimate", "behind-beat", "understated", "legato"],
    personality: ["intimate", "restrained"],
  },
  {
    id: "lana-del-rey", name: "Lana Del Rey", type: "Mezzo-soprano",
    lang: "en", low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Alternative"],
    blurb: "Cinematic, melancholic mezzo with a vintage haze.",
    songs: ["Video Games", "Summertime Sadness", "Young and Beautiful", "Born to Die", "Say Yes to Heaven"],
    voice: { brightness: 30, warmth: 70, weight: 35, breathiness: 60, roughness: 15, vibrato: 35 },
    technique: ["breathy", "soft onset", "vibrato", "slides"],
    delivery: ["behind-beat", "legato", "understated", "sustained"],
    personality: ["dreamy", "melancholic"],
  },
  {
    id: "taylor-swift", name: "Taylor Swift", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "D5", tone: "warm", genres: ["Pop", "Country", "Folk"],
    blurb: "Conversational, melodic voice built around storytelling.",
    songs: ["Love Story", "Blank Space", "Anti-Hero", "Cruel Summer", "Fortnight"],
    voice: { brightness: 55, warmth: 55, weight: 35, breathiness: 40, roughness: 10, vibrato: 30 },
    technique: ["straight tone", "breathy", "soft onset", "slides"],
    delivery: ["conversational", "rhythmic", "controlled", "precise"],
    personality: ["conversational", "polished"],
  },
  {
    id: "sia", name: "Sia", type: "Mezzo-soprano",
    lang: "en", low: "A3", high: "E5", tone: "bright", genres: ["Pop"],
    blurb: "Explosive, raspy belter with huge, cathartic choruses.",
    songs: ["Chandelier", "Elastic Heart", "Cheap Thrills", "Titanium", "Unstoppable"],
    voice: { brightness: 70, warmth: 45, weight: 65, breathiness: 20, roughness: 70, vibrato: 60 },
    technique: ["belt", "rasp", "vibrato", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "elastic"],
    personality: ["raw", "commanding"],
  },
  {
    id: "celine-dion", name: "Céline Dion", type: "Soprano",
    lang: "en", low: "B2", high: "C6", tone: "bright", genres: ["Pop"],
    blurb: "Powerhouse balladeer — enormous range, precision and drama.",
    songs: ["My Heart Will Go On", "The Power of Love", "It's All Coming Back to Me Now", "Because You Loved Me", "I'm Alive"],
    voice: { brightness: 70, warmth: 55, weight: 70, breathiness: 10, roughness: 10, vibrato: 85 },
    technique: ["belt", "vibrato", "slides", "runs"],
    delivery: ["dramatic", "powerful", "sustained", "precise"],
    personality: ["polished", "theatrical"],
  },
  {
    id: "mariah-carey", name: "Mariah Carey", type: "Soprano",
    lang: "en", low: "F3", high: "G6", tone: "bright", genres: ["Pop", "R&B"],
    blurb: "Five-octave icon — melismatic runs and a signature whistle register.",
    songs: ["Hero", "We Belong Together", "Always Be My Baby", "All I Want for Christmas Is You", "Fantasy"],
    voice: { brightness: 70, warmth: 55, weight: 50, breathiness: 30, roughness: 10, vibrato: 70 },
    technique: ["runs", "falsetto", "vibrato", "breathy"],
    delivery: ["precise", "dynamic", "elastic", "sustained"],
    personality: ["crystalline", "virtuosic"],
  },
  {
    id: "john-legend", name: "John Legend", type: "Tenor",
    lang: "en", low: "C3", high: "A4", tone: "warm", genres: ["R&B", "Soul", "Pop"],
    blurb: "Smooth soul tenor — piano-led, romantic and refined.",
    songs: ["All of Me", "Ordinary People", "Tonight (Best You Ever Had)", "Nervous", "Green Light"],
    voice: { brightness: 50, warmth: 75, weight: 55, breathiness: 25, roughness: 20, vibrato: 65 },
    technique: ["vibrato", "runs", "belt", "slides"],
    delivery: ["legato", "intimate", "controlled", "rhythmic"],
    personality: ["smooth", "soulful"],
  },
  {
    id: "stevie-wonder", name: "Stevie Wonder", type: "Tenor",
    lang: "en", low: "C3", high: "C5", tone: "bright", genres: ["Soul", "Funk", "R&B"],
    blurb: "Joyful, elastic tenor with impeccable groove and melodic invention.",
    songs: ["Isn't She Lovely", "Superstition", "Signed, Sealed, Delivered", "I Just Called to Say I Love You", "Sir Duke"],
    voice: { brightness: 65, warmth: 65, weight: 50, breathiness: 15, roughness: 25, vibrato: 70 },
    technique: ["runs", "vibrato", "belt", "scoops"],
    delivery: ["rhythmic", "elastic", "dynamic", "precise"],
    personality: ["playful", "soulful"],
  },
  {
    id: "leonard-cohen", name: "Leonard Cohen", type: "Bass-baritone",
    lang: "en", low: "D2", high: "C4", tone: "dark", genres: ["Folk", "Rock"],
    blurb: "Gravelly, poetic low voice — half sung, half spoken, all gravitas.",
    songs: ["Hallelujah", "Suzanne", "Dance Me to the End of Love", "Famous Blue Raincoat", "You Want It Darker"],
    voice: { brightness: 15, warmth: 65, weight: 85, breathiness: 35, roughness: 60, vibrato: 10 },
    technique: ["straight tone", "vocal fry", "firm onset"],
    delivery: ["conversational", "restrained", "behind-beat", "understated"],
    personality: ["earthy", "restrained"],
  },
  {
    id: "toni-braxton", name: "Toni Braxton", type: "Contralto",
    lang: "en", low: "C3", high: "C5", tone: "dark", genres: ["R&B", "Pop"],
    blurb: "Sultry, velvety contralto — one of R&B's richest low voices.",
    songs: ["Un-Break My Heart", "Breathe Again", "He Wasn't Man Enough", "You're Makin' Me High", "Another Sad Love Song"],
    voice: { brightness: 30, warmth: 80, weight: 70, breathiness: 35, roughness: 25, vibrato: 60 },
    technique: ["vibrato", "runs", "slides", "breathy"],
    delivery: ["legato", "sustained", "intimate", "dramatic"],
    personality: ["sensual", "smoky"],
  },
  {
    id: "shawn-mendes", name: "Shawn Mendes", type: "Tenor",
    lang: "en", low: "B2", high: "B4", tone: "warm", genres: ["Pop"],
    blurb: "Bright pop tenor with an easy falsetto and guitar-driven hooks.",
    songs: ["Stitches", "Mercy", "There's Nothing Holdin' Me Back", "Se\u00f1orita", "In My Blood"],
    voice: { brightness: 65, warmth: 55, weight: 35, breathiness: 35, roughness: 15, vibrato: 40 },
    technique: ["falsetto", "breathy", "soft onset", "runs"],
    delivery: ["rhythmic", "conversational", "controlled", "legato"],
    personality: ["polished", "earnest"],
  },
  {
    id: "dua-lipa", name: "Dua Lipa", type: "Mezzo-soprano",
    lang: "en", low: "F3", high: "B4", tone: "dark", genres: ["Pop", "Dance"],
    blurb: "Cool, low-slung mezzo made for disco-pop grooves.",
    songs: ["Levitating", "Don't Start Now", "New Rules", "Houdini", "Training Season"],
    voice: { brightness: 35, warmth: 60, weight: 45, breathiness: 30, roughness: 15, vibrato: 20 },
    technique: ["straight tone", "firm onset", "vocal fry"],
    delivery: ["rhythmic", "controlled", "precise", "understated"],
    personality: ["cool", "restrained"],
  },
  {
    id: "rihanna", name: "Rihanna", type: "Alto",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Dance"],
    blurb: "Distinctive, edgy alto with instantly memorable hooks.",
    songs: ["Diamonds", "Stay", "Umbrella", "Lift Me Up", "Love on the Brain"],
    voice: { brightness: 55, warmth: 55, weight: 50, breathiness: 30, roughness: 30, vibrato: 35 },
    technique: ["straight tone", "slides", "rasp", "belt"],
    delivery: ["rhythmic", "precise", "controlled", "conversational"],
    personality: ["cool", "edgy"],
  },
  {
    id: "chris-stapleton", name: "Chris Stapleton", type: "Tenor",
    lang: "en", low: "A2", high: "B4", tone: "dark", genres: ["Country", "Rock", "Blues"],
    blurb: "Whiskey-soaked country tenor with serious blues power.",
    songs: ["Tennessee Whiskey", "Broken Halos", "Starting Over", "White Horse", "Think I'm in Love with You"],
    voice: { brightness: 40, warmth: 65, weight: 75, breathiness: 15, roughness: 70, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["powerful", "dramatic", "sustained", "elastic"],
    personality: ["raw", "earthy"],
  },
  {
    id: "dolly-parton", name: "Dolly Parton", type: "Soprano",
    lang: "en", low: "G3", high: "D5", tone: "bright", genres: ["Country", "Pop"],
    blurb: "Sparkling country soprano with a quicksilver vibrato.",
    songs: ["Jolene", "9 to 5", "I Will Always Love You", "Here You Come Again", "Coat of Many Colors"],
    voice: { brightness: 80, warmth: 60, weight: 30, breathiness: 20, roughness: 15, vibrato: 85 },
    technique: ["vibrato", "slides", "scoops"],
    delivery: ["conversational", "rhythmic", "precise", "controlled"],
    personality: ["sparkling", "playful"],
  },
  {
    id: "aretha-franklin", name: "Aretha Franklin", type: "Mezzo-soprano",
    lang: "en", low: "F3", high: "E5", tone: "bright", genres: ["Soul", "Gospel", "R&B"],
    blurb: "The Queen of Soul — gospel fire, effortless power and total command.",
    songs: ["Respect", "(You Make Me Feel Like) A Natural Woman", "Think", "I Say a Little Prayer", "Chain of Fools"],
    voice: { brightness: 70, warmth: 65, weight: 70, breathiness: 10, roughness: 35, vibrato: 75 },
    technique: ["belt", "runs", "vibrato", "scoops"],
    delivery: ["powerful", "dynamic", "elastic", "dramatic"],
    personality: ["commanding", "soulful"],
  },
  {
    id: "thom-yorke", name: "Thom Yorke", type: "Tenor",
    lang: "en", low: "B2", high: "A4", tone: "bright", genres: ["Alternative", "Rock"],
    blurb: "Ethereal alt-rock tenor — a soaring falsetto and elastic, expressive phrasing.",
    songs: ["Creep", "Karma Police", "Fake Plastic Trees", "No Surprises", "Everything in Its Right Place"],
    voice: { brightness: 65, warmth: 40, weight: 30, breathiness: 40, roughness: 20, vibrato: 60 },
    technique: ["falsetto", "vibrato", "slides", "soft onset"],
    delivery: ["elastic", "dramatic", "legato", "sustained"],
    personality: ["ethereal", "vulnerable"],
  },
  {
    id: "olivia-rodrigo", name: "Olivia Rodrigo", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "D5", tone: "warm", genres: ["Pop", "Alternative", "Rock"],
    blurb: "Diary-honest pop-rock voice — conversational verses that break into cathartic choruses.",
    songs: ["drivers license", "good 4 u", "vampire", "deja vu", "traitor"],
    voice: { brightness: 55, warmth: 55, weight: 40, breathiness: 45, roughness: 20, vibrato: 35 },
    technique: ["breathy", "soft onset", "belt", "straight tone"],
    delivery: ["conversational", "dynamic", "dramatic", "intimate"],
    personality: ["honest", "vulnerable"],
  },
  {
    id: "sabrina-carpenter", name: "Sabrina Carpenter", type: "Soprano",
    lang: "en", low: "A3", high: "E5", tone: "bright", genres: ["Pop"],
    blurb: "Playful, bright pop soprano with a sweet head voice and cheeky, precise phrasing.",
    songs: ["Espresso", "Please Please Please", "Taste", "Nonsense", "Manchild"],
    voice: { brightness: 70, warmth: 55, weight: 30, breathiness: 35, roughness: 10, vibrato: 45 },
    technique: ["runs", "falsetto", "vibrato", "soft onset"],
    delivery: ["rhythmic", "precise", "controlled", "conversational"],
    personality: ["playful", "sparkling"],
  },
  {
    id: "chappell-roan", name: "Chappell Roan", type: "Soprano",
    lang: "en", low: "G3", high: "E5", tone: "bright", genres: ["Pop", "Dance"],
    blurb: "Theatrical camp-pop soprano — huge belts and a soaring, elastic top.",
    songs: ["Good Luck, Babe!", "Pink Pony Club", "HOT TO GO!", "Red Wine Supernova", "The Giver"],
    voice: { brightness: 70, warmth: 50, weight: 55, breathiness: 20, roughness: 15, vibrato: 60 },
    technique: ["belt", "vibrato", "falsetto", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "elastic"],
    personality: ["theatrical", "bold"],
  },
  {
    id: "harry-styles", name: "Harry Styles", type: "Tenor",
    lang: "en", low: "B2", high: "B4", tone: "warm", genres: ["Pop", "Rock"],
    blurb: "Warm, easygoing tenor with a rock edge and a relaxed, breezy delivery.",
    songs: ["As It Was", "Watermelon Sugar", "Adore You", "Sign of the Times", "Late Night Talking"],
    voice: { brightness: 50, warmth: 65, weight: 50, breathiness: 30, roughness: 30, vibrato: 45 },
    technique: ["belt", "vibrato", "slides", "falsetto"],
    delivery: ["legato", "rhythmic", "controlled", "dramatic"],
    personality: ["charming", "relaxed"],
  },
  {
    id: "the-weeknd", name: "The Weeknd", type: "Tenor",
    lang: "en", low: "C3", high: "C5", tone: "bright", genres: ["R&B", "Pop"],
    blurb: "Silky, airy high tenor — 80s-tinged falsetto and cinematic hooks.",
    songs: ["Blinding Lights", "Die for You", "Save Your Tears", "Starboy", "Timeless"],
    voice: { brightness: 65, warmth: 55, weight: 30, breathiness: 50, roughness: 10, vibrato: 55 },
    technique: ["falsetto", "vibrato", "breathy", "runs"],
    delivery: ["legato", "sustained", "dramatic", "precise"],
    personality: ["dreamy", "cinematic"],
  },
  {
    id: "sza", name: "SZA", type: "Alto",
    lang: "en", low: "F3", high: "C5", tone: "warm", genres: ["R&B", "Pop"],
    blurb: "Conversational, elastic alto — jazzy melodies and effortlessly off-kilter phrasing.",
    songs: ["Kill Bill", "Snooze", "Good Days", "Saturn", "Nobody Gets Me"],
    voice: { brightness: 45, warmth: 70, weight: 40, breathiness: 50, roughness: 15, vibrato: 30 },
    technique: ["breathy", "runs", "slides", "soft onset"],
    delivery: ["conversational", "behind-beat", "elastic", "intimate"],
    personality: ["dreamy", "candid"],
  },
  {
    id: "doja-cat", name: "Doja Cat", type: "Alto",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Hip-Hop"],
    blurb: "Chameleonic voice — sweet melodic hooks one bar, rap swagger the next.",
    songs: ["Say So", "Kiss Me More", "Paint the Town Red", "Woman", "Agora Hills"],
    voice: { brightness: 55, warmth: 60, weight: 40, breathiness: 35, roughness: 20, vibrato: 30 },
    technique: ["straight tone", "breathy", "runs", "slides"],
    delivery: ["rhythmic", "conversational", "precise", "controlled"],
    personality: ["playful", "versatile"],
  },
  {
    id: "miley-cyrus", name: "Miley Cyrus", type: "Alto",
    lang: "en", low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Rock"],
    blurb: "Husky, smoky alto with rock grit and a big, gutsy belt.",
    songs: ["Flowers", "Wrecking Ball", "Midnight Sky", "Angels Like You", "Used to Be Young"],
    voice: { brightness: 40, warmth: 60, weight: 65, breathiness: 25, roughness: 60, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["powerful", "dramatic", "dynamic", "conversational"],
    personality: ["raw", "gutsy"],
  },
  {
    id: "benson-boone", name: "Benson Boone", type: "Tenor",
    lang: "en", low: "C3", high: "C5", tone: "bright", genres: ["Pop", "Rock"],
    blurb: "Powerhouse pop tenor — huge belts, soaring falsetto and theatrical drama.",
    songs: ["Beautiful Things", "Slow It Down", "Mystical Magical", "In the Stars", "Sorry I'm Here for Someone Else"],
    voice: { brightness: 65, warmth: 55, weight: 55, breathiness: 20, roughness: 25, vibrato: 65 },
    technique: ["belt", "falsetto", "vibrato", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "sustained"],
    personality: ["theatrical", "earnest"],
  },
  {
    id: "teddy-swims", name: "Teddy Swims", type: "Tenor",
    lang: "en", low: "A2", high: "B4", tone: "dark", genres: ["Soul", "Pop", "R&B"],
    blurb: "Gravel-and-honey soul tenor — raspy, warm and enormously emotive.",
    songs: ["Lose Control", "The Door", "Bad Dreams", "Some Things I'll Never Know", "Guilty"],
    voice: { brightness: 40, warmth: 75, weight: 70, breathiness: 20, roughness: 70, vibrato: 60 },
    technique: ["rasp", "belt", "vibrato", "runs"],
    delivery: ["powerful", "dramatic", "sustained", "legato"],
    personality: ["soulful", "raw"],
  },
  {
    id: "noah-kahan", name: "Noah Kahan", type: "Tenor",
    lang: "en", low: "B2", high: "A4", tone: "warm", genres: ["Folk", "Pop"],
    blurb: "Earnest folk-pop tenor — gravelly edges, stomping choruses and storytelling verses.",
    songs: ["Stick Season", "Dial Drunk", "Northern Attitude", "She Calls Me Back", "Everywhere, Everything"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 30, roughness: 45, vibrato: 35 },
    technique: ["rasp", "straight tone", "belt", "slides"],
    delivery: ["conversational", "dynamic", "rhythmic", "dramatic"],
    personality: ["earnest", "earthy"],
  },
  {
    id: "post-malone", name: "Post Malone", type: "Baritone",
    lang: "en", low: "G2", high: "G4", tone: "warm", genres: ["Pop", "Hip-Hop", "Country"],
    blurb: "Laid-back baritone with a sad-eyed croon and a surprising country warmth.",
    songs: ["Circles", "Sunflower", "I Had Some Help", "Better Now", "Chemical"],
    voice: { brightness: 45, warmth: 65, weight: 55, breathiness: 35, roughness: 35, vibrato: 50 },
    technique: ["vibrato", "slides", "breathy", "straight tone"],
    delivery: ["behind-beat", "conversational", "legato", "understated"],
    personality: ["melancholic", "laid-back"],
  },
  {
    id: "gracie-abrams", name: "Gracie Abrams", type: "Soprano",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Hushed, breathy whisper-pop — diaristic and close to the mic.",
    songs: ["I Love You, I'm Sorry", "That's So True", "Risk", "Close to You", "Feels Like"],
    voice: { brightness: 50, warmth: 55, weight: 20, breathiness: 75, roughness: 10, vibrato: 15 },
    technique: ["breathy", "soft onset", "straight tone", "vocal fry"],
    delivery: ["intimate", "conversational", "understated", "legato"],
    personality: ["intimate", "confessional"],
  },
  {
    id: "tate-mcrae", name: "Tate McRae", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "Dance"],
    blurb: "Cool, breathy dance-pop mezzo with a conversational, rhythmic edge.",
    songs: ["Greedy", "Exes", "You Broke Me First", "Sports Car", "Revolving Door"],
    voice: { brightness: 50, warmth: 50, weight: 30, breathiness: 60, roughness: 15, vibrato: 20 },
    technique: ["breathy", "straight tone", "soft onset", "vocal fry"],
    delivery: ["rhythmic", "understated", "controlled", "precise"],
    personality: ["cool", "sleek"],
  },
  {
    id: "lady-gaga", name: "Lady Gaga", type: "Mezzo-soprano",
    lang: "en", low: "F3", high: "E5", tone: "bright", genres: ["Pop", "Dance", "Jazz"],
    blurb: "Theatrical powerhouse — brassy belts, jazz phrasing and total vocal control.",
    songs: ["Shallow", "Die with a Smile", "Abracadabra", "Bad Romance", "Always Remember Us This Way"],
    voice: { brightness: 65, warmth: 60, weight: 70, breathiness: 15, roughness: 30, vibrato: 75 },
    technique: ["belt", "vibrato", "slides", "runs"],
    delivery: ["dramatic", "powerful", "dynamic", "precise"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "rose", name: "ROSÉ", type: "Soprano",
    lang: "en", low: "A3", high: "E5", tone: "bright", genres: ["Pop", "K-Pop"],
    blurb: "Distinctive, plaintive soprano with an airy, bittersweet top.",
    songs: ["APT.", "Toxic Till the End", "On the Ground", "Number One Girl", "Gone"],
    voice: { brightness: 75, warmth: 45, weight: 25, breathiness: 45, roughness: 10, vibrato: 40 },
    technique: ["breathy", "vibrato", "soft onset", "straight tone"],
    delivery: ["legato", "sustained", "controlled", "intimate"],
    personality: ["wistful", "distinctive"],
  },
  {
    id: "tyla", name: "Tyla", type: "Alto",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Afropop"],
    blurb: "Silky, sultry amapiano-pop alto — smooth, breathy and rhythmically playful.",
    songs: ["Water", "Push 2 Start", "Jump", "Truth or Dare", "Art"],
    voice: { brightness: 50, warmth: 65, weight: 35, breathiness: 55, roughness: 10, vibrato: 20 },
    technique: ["breathy", "soft onset", "straight tone", "runs"],
    delivery: ["rhythmic", "intimate", "controlled", "understated"],
    personality: ["sultry", "smooth"],
  },
  {
    id: "justin-bieber", name: "Justin Bieber", type: "Tenor",
    lang: "en", low: "C3", high: "B4", tone: "warm", genres: ["Pop", "R&B"],
    blurb: "Light, agile pop-R&B tenor with a silky falsetto and easy runs.",
    songs: ["Peaches", "Ghost", "Love Yourself", "Daisies", "Yukon"],
    voice: { brightness: 60, warmth: 60, weight: 35, breathiness: 40, roughness: 10, vibrato: 40 },
    technique: ["falsetto", "runs", "breathy", "soft onset"],
    delivery: ["rhythmic", "legato", "controlled", "intimate"],
    personality: ["smooth", "polished"],
  },
  {
    id: "zach-bryan", name: "Zach Bryan", type: "Baritone",
    lang: "en", low: "A2", high: "A4", tone: "warm", genres: ["Country", "Folk"],
    blurb: "Ragged, heartfelt country-folk voice — cracked edges and raw sincerity.",
    songs: ["Something in the Orange", "I Remember Everything", "Pink Skies", "Heading South", "28"],
    voice: { brightness: 45, warmth: 60, weight: 55, breathiness: 30, roughness: 55, vibrato: 25 },
    technique: ["rasp", "straight tone", "firm onset", "slides"],
    delivery: ["conversational", "dramatic", "dynamic", "restrained"],
    personality: ["raw", "earnest"],
  },
  {
    id: "morgan-wallen", name: "Morgan Wallen", type: "Baritone",
    lang: "en", low: "A2", high: "A4", tone: "warm", genres: ["Country", "Pop"],
    blurb: "Twangy, gravelly country baritone built for radio hooks.",
    songs: ["Last Night", "Whiskey Glasses", "I Had Some Help", "Love Somebody", "Wasted on You"],
    voice: { brightness: 50, warmth: 55, weight: 55, breathiness: 20, roughness: 50, vibrato: 35 },
    technique: ["rasp", "straight tone", "slides", "firm onset"],
    delivery: ["rhythmic", "conversational", "controlled", "precise"],
    personality: ["twangy", "easygoing"],
  },
  {
    id: "alex-warren", name: "Alex Warren", type: "Tenor",
    lang: "en", low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Anthemic folk-pop tenor — hushed verses that swell into huge, hymn-like choruses.",
    songs: ["Ordinary", "Carry You Home", "Burning Down", "Bloodline", "Eternity"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 35, roughness: 30, vibrato: 50 },
    technique: ["belt", "breathy", "vibrato", "soft onset"],
    delivery: ["dramatic", "dynamic", "sustained", "legato"],
    personality: ["anthemic", "earnest"],
  },
  {
    id: "lola-young", name: "Lola Young", type: "Alto",
    lang: "en", low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Soul", "Alternative"],
    blurb: "Husky, unfiltered London alto — raspy, candid and stylishly messy.",
    songs: ["Messy", "Conceited", "Wish You Were Dead", "One Thing", "Big Brown Eyes"],
    voice: { brightness: 40, warmth: 60, weight: 50, breathiness: 40, roughness: 55, vibrato: 30 },
    technique: ["rasp", "straight tone", "slides", "breathy"],
    delivery: ["conversational", "dynamic", "elastic", "intimate"],
    personality: ["candid", "raw"],
  },
  {
    id: "raye", name: "RAYE", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "D5", tone: "warm", genres: ["Pop", "R&B", "Jazz"],
    blurb: "Jazz-schooled pop mezzo — theatrical dynamics, big belts and razor diction.",
    songs: ["Escapism.", "Worth It.", "Prada", "Ice Cream Man.", "Genesis."],
    voice: { brightness: 60, warmth: 60, weight: 55, breathiness: 25, roughness: 25, vibrato: 65 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["dramatic", "dynamic", "precise", "elastic"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "olivia-dean", name: "Olivia Dean", type: "Mezzo-soprano",
    lang: "en", low: "G3", high: "C5", tone: "warm", genres: ["Soul", "Pop", "Jazz"],
    blurb: "Sunlit, velvety soul-pop voice — warm, relaxed and effortlessly tuneful.",
    songs: ["Dive", "Man I Need", "Nice to Each Other", "The Hardest Part", "Ladies Room"],
    voice: { brightness: 50, warmth: 80, weight: 45, breathiness: 35, roughness: 10, vibrato: 45 },
    technique: ["vibrato", "soft onset", "runs", "slides"],
    delivery: ["legato", "controlled", "intimate", "rhythmic"],
    personality: ["warm", "easygoing"],
  },
  {
    id: "myles-smith", name: "Myles Smith", type: "Tenor",
    lang: "en", low: "B2", high: "A4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Big-hearted stadium-folk tenor with a gritty, joyful edge.",
    songs: ["Stargazing", "Nice to Meet You", "Wait for You", "My First Heartbreak", "Solo"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 25, roughness: 40, vibrato: 35 },
    technique: ["belt", "rasp", "straight tone", "slides"],
    delivery: ["dynamic", "rhythmic", "dramatic", "conversational"],
    personality: ["joyful", "earnest"],
  },
  {
    id: "bad-bunny", name: "Bad Bunny", type: "Baritone",
    lang: "es", low: "G2", high: "G4", tone: "dark", genres: ["Latin", "Reggaeton", "Pop"],
    blurb: "Low, laid-back Latin baritone — half-sung, half-rapped, effortlessly cool.",
    songs: ["DtMF", "Tití Me Preguntó", "Me Porto Bonito", "Baile Inolvidable", "Dakiti"],
    voice: { brightness: 35, warmth: 55, weight: 60, breathiness: 30, roughness: 30, vibrato: 15 },
    technique: ["straight tone", "vocal fry", "firm onset"],
    delivery: ["rhythmic", "conversational", "understated", "behind-beat"],
    personality: ["cool", "laid-back"],
  },
  {
    id: "shakira", name: "Shakira", type: "Alto",
    lang: "es", low: "F3", high: "C5", tone: "bright", genres: ["Latin", "Pop"],
    blurb: "Unmistakable yodel-tinged alto — husky lows, sudden breaks and bright pop hooks.",
    songs: ["Hips Don't Lie", "Whenever, Wherever", "Soltera", "Waka Waka", "TQG"],
    voice: { brightness: 60, warmth: 55, weight: 45, breathiness: 25, roughness: 45, vibrato: 60 },
    technique: ["vibrato", "rasp", "slides", "scoops"],
    delivery: ["rhythmic", "dynamic", "elastic", "dramatic"],
    personality: ["distinctive", "fiery"],
  },
  {
    id: "rosalia", name: "Rosalía", type: "Mezzo-soprano",
    lang: "es", low: "A3", high: "D5", tone: "bright", genres: ["Pop", "Flamenco", "Latin"],
    blurb: "Flamenco-schooled pop voice — ornamented melismas, raw edges and cool restraint.",
    songs: ["Malamente", "Con Altura", "Despechá", "La Fama", "Saoko"],
    voice: { brightness: 60, warmth: 55, weight: 40, breathiness: 30, roughness: 35, vibrato: 55 },
    technique: ["runs", "vibrato", "rasp", "slides"],
    delivery: ["rhythmic", "elastic", "dramatic", "controlled"],
    personality: ["fiery", "stylish"],
  },
  {
    id: "karol-g", name: "Karol G", type: "Alto",
    lang: "es", low: "G3", high: "C5", tone: "warm", genres: ["Reggaeton", "Latin", "Pop"],
    blurb: "Warm, conversational reggaeton alto with an easy, sunlit hook sense.",
    songs: ["Provenza", "Tusa", "Mi Ex Tenía Razón", "Si Antes Te Hubiera Conocido", "Amargura"],
    voice: { brightness: 45, warmth: 65, weight: 40, breathiness: 40, roughness: 15, vibrato: 20 },
    technique: ["straight tone", "breathy", "soft onset", "slides"],
    delivery: ["rhythmic", "conversational", "controlled", "intimate"],
    personality: ["sunny", "laid-back"],
  },
  {
    id: "luis-miguel", name: "Luis Miguel", type: "Tenor",
    lang: "es", low: "A2", high: "A4", tone: "warm", genres: ["Latin", "Pop", "Bolero"],
    blurb: "El Sol — a golden, powerful Latin tenor with classic bolero polish.",
    songs: ["La Incondicional", "Ahora Te Puedes Marchar", "Por Debajo de la Mesa", "Hasta Que Me Olvides", "Culpable o No"],
    voice: { brightness: 60, warmth: 70, weight: 60, breathiness: 10, roughness: 20, vibrato: 75 },
    technique: ["vibrato", "belt", "slides", "firm onset"],
    delivery: ["dramatic", "sustained", "powerful", "precise"],
    personality: ["polished", "romantic"],
  },
  {
    id: "enrique-iglesias", name: "Enrique Iglesias", type: "Baritone",
    lang: "es", low: "A2", high: "G4", tone: "warm", genres: ["Latin", "Pop", "Dance"],
    blurb: "Husky, intimate pop baritone — breathy verses and big dance-floor hooks.",
    songs: ["Bailando", "Hero", "Duele el Corazón", "Súbeme la Radio", "El Perdedor"],
    voice: { brightness: 45, warmth: 65, weight: 50, breathiness: 55, roughness: 35, vibrato: 30 },
    technique: ["breathy", "soft onset", "straight tone", "rasp"],
    delivery: ["intimate", "rhythmic", "conversational", "understated"],
    personality: ["intimate", "romantic"],
  },
  {
    id: "alejandro-sanz", name: "Alejandro Sanz", type: "Tenor",
    lang: "es", low: "C3", high: "A4", tone: "warm", genres: ["Latin", "Pop", "Flamenco"],
    blurb: "Raspy, emotive Spanish tenor with flamenco phrasing and poetic delivery.",
    songs: ["Corazón Partío", "Amiga Mía", "Y, ¿Si Fuera Ella?", "No Es lo Mismo", "Mi Persona Favorita"],
    voice: { brightness: 50, warmth: 60, weight: 50, breathiness: 25, roughness: 60, vibrato: 55 },
    technique: ["rasp", "vibrato", "runs", "slides"],
    delivery: ["dramatic", "elastic", "dynamic", "conversational"],
    personality: ["passionate", "poetic"],
  },
  {
    id: "natalia-lafourcade", name: "Natalia Lafourcade", type: "Soprano",
    lang: "es", low: "A3", high: "D5", tone: "bright", genres: ["Latin", "Folk", "Pop"],
    blurb: "Delicate, folk-rooted Mexican soprano — clear, tender and beautifully plain-spoken.",
    songs: ["Hasta la Raíz", "Nunca Es Suficiente", "Tú Sí Sabes Quererme", "Soledad y el Mar", "De Todas las Flores"],
    voice: { brightness: 65, warmth: 65, weight: 25, breathiness: 35, roughness: 10, vibrato: 35 },
    technique: ["straight tone", "soft onset", "vibrato", "slides"],
    delivery: ["intimate", "legato", "restrained", "controlled"],
    personality: ["tender", "luminous"],
  },
  {
    id: "iu", name: "IU", type: "Soprano",
    lang: "ko", low: "A3", high: "E5", tone: "bright", genres: ["K-Pop", "Pop", "Folk"],
    blurb: "Sweet, crystalline Korean soprano — famous high notes and gentle storytelling.",
    songs: ["Good Day", "Through the Night", "Blueming", "Palette", "Love Wins All"],
    voice: { brightness: 70, warmth: 60, weight: 25, breathiness: 35, roughness: 10, vibrato: 45 },
    technique: ["vibrato", "falsetto", "soft onset", "runs"],
    delivery: ["legato", "intimate", "precise", "controlled"],
    personality: ["sweet", "crystalline"],
  },
  {
    id: "jung-kook", name: "Jung Kook", type: "Tenor",
    lang: "ko", low: "C3", high: "B4", tone: "bright", genres: ["K-Pop", "Pop", "R&B"],
    blurb: "Smooth, agile K-pop tenor — airy falsetto, clean runs and pop polish.",
    songs: ["Seven", "Standing Next to You", "Euphoria", "Still with You", "3D"],
    voice: { brightness: 65, warmth: 55, weight: 35, breathiness: 40, roughness: 10, vibrato: 45 },
    technique: ["falsetto", "runs", "breathy", "vibrato"],
    delivery: ["rhythmic", "precise", "controlled", "legato"],
    personality: ["polished", "smooth"],
  },
  {
    id: "taeyeon", name: "Taeyeon", type: "Soprano",
    lang: "ko", low: "G3", high: "E5", tone: "bright", genres: ["K-Pop", "Pop", "Ballad"],
    blurb: "Powerful, emotive K-ballad soprano with a pure tone and effortless high belts.",
    songs: ["I", "Fine", "Four Seasons", "INVU", "Weekend"],
    voice: { brightness: 70, warmth: 55, weight: 45, breathiness: 25, roughness: 15, vibrato: 60 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["dramatic", "sustained", "dynamic", "precise"],
    personality: ["emotive", "pure"],
  },
  {
    id: "baekhyun", name: "Baekhyun", type: "Tenor",
    lang: "ko", low: "C3", high: "C5", tone: "bright", genres: ["K-Pop", "R&B", "Pop"],
    blurb: "Silky R&B tenor — buttery falsetto and effortless melismatic runs.",
    songs: ["Candy", "UN Village", "Bambi", "Hurt", "Beautiful"],
    voice: { brightness: 65, warmth: 60, weight: 35, breathiness: 40, roughness: 10, vibrato: 50 },
    technique: ["falsetto", "runs", "breathy", "vibrato"],
    delivery: ["legato", "rhythmic", "controlled", "intimate"],
    personality: ["silky", "smooth"],
  },
  {
    id: "lee-hi", name: "Lee Hi", type: "Alto",
    lang: "ko", low: "F3", high: "C5", tone: "warm", genres: ["K-Pop", "R&B", "Soul"],
    blurb: "Husky, soulful Korean alto — jazzy lows and a smoky, unhurried delivery.",
    songs: ["Breathe", "Rose", "Only", "Holo", "Red Lipstick"],
    voice: { brightness: 40, warmth: 70, weight: 50, breathiness: 40, roughness: 35, vibrato: 40 },
    technique: ["breathy", "vibrato", "slides", "soft onset"],
    delivery: ["behind-beat", "intimate", "legato", "understated"],
    personality: ["smoky", "soulful"],
  },
  {
    id: "crush", name: "Crush", type: "Tenor",
    lang: "ko", low: "B2", high: "A4", tone: "warm", genres: ["K-Pop", "R&B", "Soul"],
    blurb: "Groove-first Korean R&B tenor — soft, breathy and rhythmically playful.",
    songs: ["Beautiful", "Rush Hour", "Sofa", "Oasis", "Let Us Go"],
    voice: { brightness: 55, warmth: 65, weight: 40, breathiness: 45, roughness: 15, vibrato: 35 },
    technique: ["breathy", "soft onset", "runs", "falsetto"],
    delivery: ["rhythmic", "conversational", "intimate", "controlled"],
    personality: ["groovy", "mellow"],
  },
  {
    id: "hikaru-utada", name: "Hikaru Utada", type: "Alto",
    lang: "ja", low: "G3", high: "D5", tone: "warm", genres: ["J-Pop", "R&B", "Pop"],
    blurb: "Warm, R&B-inflected J-pop alto — conversational, floating and instantly recognisable.",
    songs: ["First Love", "Automatic", "Hikari", "One Last Kiss", "Flavor of Life"],
    voice: { brightness: 50, warmth: 70, weight: 40, breathiness: 45, roughness: 10, vibrato: 40 },
    technique: ["breathy", "slides", "vibrato", "soft onset"],
    delivery: ["behind-beat", "legato", "intimate", "controlled"],
    personality: ["floating", "intimate"],
  },
  {
    id: "aimer", name: "Aimer", type: "Alto",
    lang: "ja", low: "F3", high: "C5", tone: "dark", genres: ["J-Pop", "Rock", "Ballad"],
    blurb: "Husky, whispered-to-soaring alto — smoky lows and dramatic anime-ballad climaxes.",
    songs: ["Zankyosanka", "Kataomoi", "Brave Shine", "Ref:rain", "Asa ga Kuru"],
    voice: { brightness: 40, warmth: 60, weight: 55, breathiness: 60, roughness: 50, vibrato: 50 },
    technique: ["breathy", "rasp", "belt", "vibrato"],
    delivery: ["dramatic", "dynamic", "sustained", "intimate"],
    personality: ["smoky", "dramatic"],
  },
  {
    id: "kenshi-yonezu", name: "Kenshi Yonezu", type: "Baritone",
    lang: "ja", low: "G2", high: "A4", tone: "warm", genres: ["J-Pop", "Alternative", "Rock"],
    blurb: "Deep, elastic J-pop baritone — angular melodies delivered with cool precision.",
    songs: ["Lemon", "KICK BACK", "Uma to Shika", "Peace Sign", "Sayonara"],
    voice: { brightness: 45, warmth: 60, weight: 60, breathiness: 25, roughness: 30, vibrato: 40 },
    technique: ["straight tone", "slides", "falsetto", "firm onset"],
    delivery: ["rhythmic", "precise", "elastic", "controlled"],
    personality: ["cool", "inventive"],
  },
  {
    id: "ikura", name: "ikura (YOASOBI)", type: "Soprano",
    lang: "ja", low: "A3", high: "E5", tone: "bright", genres: ["J-Pop", "Electronic", "Pop"],
    blurb: "Light, quick, ultra-clear soprano built for rapid-fire J-pop melodies.",
    songs: ["Yoru ni Kakeru", "Idol", "Gunjo", "Tabun", "Yuusha"],
    voice: { brightness: 75, warmth: 50, weight: 25, breathiness: 25, roughness: 10, vibrato: 30 },
    technique: ["straight tone", "runs", "firm onset", "falsetto"],
    delivery: ["rhythmic", "precise", "controlled", "dynamic"],
    personality: ["crisp", "bright"],
  },
  {
    id: "fujii-kaze", name: "Fujii Kaze", type: "Tenor",
    lang: "ja", low: "A2", high: "A4", tone: "warm", genres: ["J-Pop", "R&B", "Soul"],
    blurb: "Laid-back soul tenor — buttery, jazzy and playfully loose.",
    songs: ["Shinunoga E-Wa", "Kirari", "Matsuri", "Michi Teyu Ku", "Grace"],
    voice: { brightness: 50, warmth: 75, weight: 45, breathiness: 40, roughness: 15, vibrato: 45 },
    technique: ["breathy", "runs", "slides", "falsetto"],
    delivery: ["behind-beat", "elastic", "intimate", "rhythmic"],
    personality: ["mellow", "playful"],
  },
  {
    id: "ado", name: "Ado", type: "Mezzo-soprano",
    lang: "ja", low: "G3", high: "E5", tone: "bright", genres: ["J-Pop", "Rock", "Electronic"],
    blurb: "Explosive, shape-shifting mezzo — growls, screams and sweet tones in one breath.",
    songs: ["Usseewa", "New Genesis", "Odo", "Show", "Gira Gira"],
    voice: { brightness: 65, warmth: 45, weight: 55, breathiness: 20, roughness: 70, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["dramatic", "dynamic", "powerful", "elastic"],
    personality: ["explosive", "theatrical"],
  },
  {
    id: "arijit-singh", name: "Arijit Singh", type: "Tenor",
    lang: "hi", low: "B2", high: "A4", tone: "warm", genres: ["Bollywood", "Pop", "Ghazal"],
    blurb: "Bollywood's heartbreak voice — husky, tender tenor with effortless ornament.",
    songs: ["Tum Hi Ho", "Channa Mereya", "Kesariya", "Ae Dil Hai Mushkil", "Tera Yaar Hoon Main"],
    voice: { brightness: 50, warmth: 70, weight: 45, breathiness: 45, roughness: 30, vibrato: 50 },
    technique: ["breathy", "runs", "slides", "vibrato"],
    delivery: ["intimate", "legato", "dramatic", "elastic"],
    personality: ["tender", "soulful"],
  },
  {
    id: "shreya-ghoshal", name: "Shreya Ghoshal", type: "Soprano",
    lang: "hi", low: "G3", high: "E5", tone: "bright", genres: ["Bollywood", "Classical", "Pop"],
    blurb: "Classically trained soprano — sweet, precise and endlessly ornamented.",
    songs: ["Teri Meri", "Sun Raha Hai", "Deewani Mastani", "Agar Tum Mil Jao", "Ghoomar"],
    voice: { brightness: 70, warmth: 60, weight: 30, breathiness: 20, roughness: 10, vibrato: 65 },
    technique: ["runs", "vibrato", "slides", "scoops"],
    delivery: ["precise", "legato", "sustained", "controlled"],
    personality: ["sweet", "virtuosic"],
  },
  {
    id: "sonu-nigam", name: "Sonu Nigam", type: "Tenor",
    lang: "hi", low: "C3", high: "B4", tone: "bright", genres: ["Bollywood", "Pop"],
    blurb: "Versatile, powerful Bollywood tenor — soaring highs and classical grace.",
    songs: ["Kal Ho Naa Ho", "Abhi Mujh Mein Kahin", "Suraj Hua Maddham", "Sandese Aate Hai", "Main Agar Kahoon"],
    voice: { brightness: 65, warmth: 60, weight: 50, breathiness: 15, roughness: 15, vibrato: 70 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["dramatic", "sustained", "precise", "dynamic"],
    personality: ["soaring", "polished"],
  },
  {
    id: "neha-kakkar", name: "Neha Kakkar", type: "Mezzo-soprano",
    lang: "hi", low: "A3", high: "D5", tone: "bright", genres: ["Bollywood", "Pop", "Dance"],
    blurb: "Bright, punchy Bollywood pop voice made for dance-floor hooks.",
    songs: ["Dilbar", "O Saki Saki", "Aankh Marey", "Garmi", "Kala Chashma"],
    voice: { brightness: 70, warmth: 50, weight: 35, breathiness: 20, roughness: 15, vibrato: 40 },
    technique: ["belt", "straight tone", "runs", "firm onset"],
    delivery: ["rhythmic", "dynamic", "precise", "controlled"],
    personality: ["punchy", "playful"],
  },
  {
    id: "atif-aslam", name: "Atif Aslam", type: "Tenor",
    lang: "hi", low: "B2", high: "A4", tone: "warm", genres: ["Bollywood", "Pop", "Rock"],
    blurb: "Husky, gravelly tenor with rock ache and Sufi colour.",
    songs: ["Tera Hone Laga Hoon", "Jeene Laga Hoon", "Tu Jaane Na", "Dil Diyan Gallan", "Pehli Nazar Mein"],
    voice: { brightness: 45, warmth: 60, weight: 55, breathiness: 35, roughness: 60, vibrato: 45 },
    technique: ["rasp", "slides", "vibrato", "belt"],
    delivery: ["dramatic", "sustained", "elastic", "intimate"],
    personality: ["gravelly", "passionate"],
  },
  {
    id: "lata-mangeshkar", name: "Lata Mangeshkar", type: "Soprano",
    lang: "hi", low: "A3", high: "E5", tone: "bright", genres: ["Bollywood", "Classical"],
    blurb: "The nightingale of India — pure, high, immaculately controlled soprano.",
    songs: ["Lag Jaa Gale", "Ajeeb Dastan Hai Yeh", "Tere Bina Zindagi Se", "Pyar Kiya To Darna Kya", "Tujhe Dekha To"],
    voice: { brightness: 75, warmth: 55, weight: 25, breathiness: 15, roughness: 10, vibrato: 60 },
    technique: ["vibrato", "runs", "slides", "straight tone"],
    delivery: ["precise", "legato", "sustained", "controlled"],
    personality: ["pure", "timeless"],
  },
  {
    id: "kishore-kumar", name: "Kishore Kumar", type: "Baritone",
    lang: "hi", low: "G2", high: "G4", tone: "warm", genres: ["Bollywood", "Pop"],
    blurb: "Playful, yodelling baritone — warm, mischievous and utterly natural.",
    songs: ["Pal Pal Dil Ke Paas", "Roop Tera Mastana", "Mere Sapno Ki Rani", "Chala Jata Hoon", "Yeh Shaam Mastani"],
    voice: { brightness: 50, warmth: 75, weight: 55, breathiness: 20, roughness: 25, vibrato: 50 },
    technique: ["vibrato", "slides", "scoops", "firm onset"],
    delivery: ["conversational", "rhythmic", "elastic", "dramatic"],
    personality: ["playful", "warm"],
  },
  {
    id: "edith-piaf", name: "Édith Piaf", type: "Mezzo-soprano",
    lang: "fr", low: "G3", high: "D5", tone: "bright", genres: ["Chanson", "Pop"],
    blurb: "The little sparrow — huge, trembling vibrato and heart-on-sleeve drama.",
    songs: ["La Vie en rose", "Non, je ne regrette rien", "Hymne à l'amour", "Milord", "Padam, padam"],
    voice: { brightness: 65, warmth: 55, weight: 55, breathiness: 10, roughness: 35, vibrato: 90 },
    technique: ["vibrato", "belt", "firm onset", "slides"],
    delivery: ["dramatic", "powerful", "sustained", "dynamic"],
    personality: ["dramatic", "iconic"],
  },
  {
    id: "stromae", name: "Stromae", type: "Baritone",
    lang: "fr", low: "A2", high: "A4", tone: "warm", genres: ["Pop", "Electronic", "Hip-Hop"],
    blurb: "Deadpan, elastic Belgian baritone — half-spoken verses, hooky sung choruses.",
    songs: ["Alors on danse", "Papaoutai", "Formidable", "Santé", "Tous les mêmes"],
    voice: { brightness: 50, warmth: 55, weight: 55, breathiness: 20, roughness: 25, vibrato: 20 },
    technique: ["straight tone", "firm onset", "slides", "vocal fry"],
    delivery: ["rhythmic", "conversational", "precise", "restrained"],
    personality: ["deadpan", "witty"],
  },
  {
    id: "aya-nakamura", name: "Aya Nakamura", type: "Alto",
    lang: "fr", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Afropop"],
    blurb: "Cool, low-slung Afro-pop alto — clipped phrasing and unstoppable hooks.",
    songs: ["Djadja", "Pookie", "Copines", "Jolie nana", "Dégaine"],
    voice: { brightness: 45, warmth: 60, weight: 45, breathiness: 35, roughness: 15, vibrato: 15 },
    technique: ["straight tone", "firm onset", "slides", "breathy"],
    delivery: ["rhythmic", "understated", "controlled", "conversational"],
    personality: ["cool", "sleek"],
  },
  {
    id: "charles-aznavour", name: "Charles Aznavour", type: "Baritone",
    lang: "fr", low: "A2", high: "G4", tone: "warm", genres: ["Chanson", "Jazz"],
    blurb: "Intimate, conversational chanson baritone — a storyteller first.",
    songs: ["La Bohème", "She", "Emmenez-moi", "Hier encore", "For Me Formidable"],
    voice: { brightness: 45, warmth: 75, weight: 55, breathiness: 25, roughness: 30, vibrato: 55 },
    technique: ["vibrato", "slides", "soft onset", "straight tone"],
    delivery: ["conversational", "legato", "intimate", "dramatic"],
    personality: ["intimate", "poetic"],
  },
  {
    id: "zaz", name: "Zaz", type: "Mezzo-soprano",
    lang: "fr", low: "G3", high: "D5", tone: "bright", genres: ["Chanson", "Jazz", "Pop"],
    blurb: "Gypsy-jazz-tinged mezzo — raspy, joyful and rhythmically loose.",
    songs: ["Je veux", "On ira", "Éblouie par la nuit", "Qué vendrá", "Si jamais j'oublie"],
    voice: { brightness: 60, warmth: 60, weight: 45, breathiness: 20, roughness: 55, vibrato: 50 },
    technique: ["rasp", "vibrato", "scoops", "slides"],
    delivery: ["rhythmic", "elastic", "dynamic", "conversational"],
    personality: ["joyful", "raspy"],
  },
  {
    id: "indila", name: "Indila", type: "Soprano",
    lang: "fr", low: "A3", high: "D5", tone: "bright", genres: ["Pop", "Chanson"],
    blurb: "Ethereal, breathy pop soprano with a wistful, cinematic sweep.",
    songs: ["Dernière danse", "Tourner dans le vide", "S.O.S", "Love Story", "Run Run"],
    voice: { brightness: 65, warmth: 55, weight: 30, breathiness: 60, roughness: 10, vibrato: 40 },
    technique: ["breathy", "vibrato", "soft onset", "slides"],
    delivery: ["dramatic", "legato", "intimate", "sustained"],
    personality: ["ethereal", "wistful"],
  },
  {
    id: "angele", name: "Angèle", type: "Mezzo-soprano",
    lang: "fr", low: "G3", high: "C5", tone: "warm", genres: ["Pop", "Electronic"],
    blurb: "Light, conversational Belgian pop voice — soft, sly and effortlessly catchy.",
    songs: ["Balance ton quoi", "Tout oublier", "Bruxelles je t'aime", "Fever", "Démons"],
    voice: { brightness: 55, warmth: 60, weight: 30, breathiness: 50, roughness: 10, vibrato: 20 },
    technique: ["breathy", "soft onset", "straight tone", "slides"],
    delivery: ["conversational", "understated", "rhythmic", "intimate"],
    personality: ["sly", "breezy"],
  },
  {
    id: "anitta", name: "Anitta", type: "Alto",
    lang: "pt", low: "G3", high: "C5", tone: "warm", genres: ["Funk", "Pop", "Latin"],
    blurb: "Sultry Brazilian funk-pop alto — rhythmic, breathy and club-ready.",
    songs: ["Envolver", "Vai Malandra", "Girl from Rio", "Downtown", "Show das Poderosas"],
    voice: { brightness: 50, warmth: 60, weight: 40, breathiness: 50, roughness: 15, vibrato: 20 },
    technique: ["breathy", "straight tone", "firm onset", "slides"],
    delivery: ["rhythmic", "controlled", "understated", "precise"],
    personality: ["sultry", "confident"],
  },
  {
    id: "marisa-monte", name: "Marisa Monte", type: "Mezzo-soprano",
    lang: "pt", low: "G3", high: "D5", tone: "warm", genres: ["MPB", "Samba", "Pop"],
    blurb: "Velvet MPB mezzo — serene, precise and effortlessly warm.",
    songs: ["Ainda Bem", "Amor I Love You", "Beija Eu", "Velha Infância", "Bem Que Se Quis"],
    voice: { brightness: 55, warmth: 80, weight: 40, breathiness: 30, roughness: 10, vibrato: 45 },
    technique: ["vibrato", "soft onset", "slides", "straight tone"],
    delivery: ["legato", "intimate", "controlled", "restrained"],
    personality: ["serene", "velvety"],
  },
  {
    id: "caetano-veloso", name: "Caetano Veloso", type: "Tenor",
    lang: "pt", low: "C3", high: "A4", tone: "warm", genres: ["MPB", "Bossa Nova", "Tropicália"],
    blurb: "Gentle, conversational tenor — the intimate poetry of tropicália.",
    songs: ["Sozinho", "Você É Linda", "O Leãozinho", "Sampa", "Cajuína"],
    voice: { brightness: 50, warmth: 75, weight: 40, breathiness: 35, roughness: 15, vibrato: 40 },
    technique: ["soft onset", "straight tone", "slides", "vibrato"],
    delivery: ["conversational", "legato", "intimate", "understated"],
    personality: ["poetic", "gentle"],
  },
  {
    id: "elis-regina", name: "Elis Regina", type: "Mezzo-soprano",
    lang: "pt", low: "G3", high: "D5", tone: "bright", genres: ["MPB", "Jazz", "Bossa Nova"],
    blurb: "Fierce, dynamic MPB mezzo — dazzling phrasing and emotional daring.",
    songs: ["Águas de Março", "Como Nossos Pais", "O Bêbado e a Equilibrista", "Madalena", "Upa Neguinho"],
    voice: { brightness: 65, warmth: 60, weight: 50, breathiness: 15, roughness: 25, vibrato: 65 },
    technique: ["vibrato", "runs", "scoops", "belt"],
    delivery: ["dramatic", "elastic", "dynamic", "precise"],
    personality: ["fierce", "virtuosic"],
  },
  {
    id: "seu-jorge", name: "Seu Jorge", type: "Baritone",
    lang: "pt", low: "G2", high: "G4", tone: "dark", genres: ["Samba", "MPB", "Soul"],
    blurb: "Deep, smoky samba-soul baritone with a warm, unhurried groove.",
    songs: ["Burguesinha", "Amiga da Minha Mulher", "Mina do Condomínio", "Tive Razão", "Carolina"],
    voice: { brightness: 35, warmth: 75, weight: 70, breathiness: 30, roughness: 35, vibrato: 30 },
    technique: ["straight tone", "vocal fry", "slides", "soft onset"],
    delivery: ["behind-beat", "rhythmic", "intimate", "restrained"],
    personality: ["smoky", "laid-back"],
  },
  {
    id: "ludmilla", name: "Ludmilla", type: "Alto",
    lang: "pt", low: "G3", high: "C5", tone: "warm", genres: ["Funk", "Pop", "R&B"],
    blurb: "Powerful Brazilian funk and pagode alto — big belts and street-smart swagger.",
    songs: ["Maldivas", "Cheguei", "Din Din Din", "Rainha da Favela", "Verdinha"],
    voice: { brightness: 50, warmth: 60, weight: 55, breathiness: 20, roughness: 25, vibrato: 45 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["rhythmic", "dynamic", "powerful", "precise"],
    personality: ["bold", "swaggering"],
  },
  {
    id: "jay-chou", name: "Jay Chou", type: "Tenor",
    lang: "zh", low: "B2", high: "A4", tone: "warm", genres: ["Mandopop", "R&B", "Pop"],
    blurb: "Mumbling-cool Mandopop tenor — R&B phrasing wrapped around classical melodies.",
    songs: ["Qing Hua Ci", "Gao Bai Qi Qiu", "An Jing", "Dao Xiang", "Qi Li Xiang"],
    voice: { brightness: 50, warmth: 65, weight: 45, breathiness: 45, roughness: 15, vibrato: 35 },
    technique: ["breathy", "slides", "falsetto", "soft onset"],
    delivery: ["behind-beat", "conversational", "legato", "understated"],
    personality: ["cool", "inventive"],
  },
  {
    id: "teresa-teng", name: "Teresa Teng", type: "Soprano",
    lang: "zh", low: "A3", high: "D5", tone: "bright", genres: ["Mandopop", "Ballad", "Folk"],
    blurb: "Sweet, gentle Mandopop soprano — soft vibrato and timeless warmth.",
    songs: ["Yue Liang Dai Biao Wo De Xin", "Tian Mi Mi", "Wo Zhi Zai Hu Ni", "Xiao Cheng Gu Shi", "Dan Yuan Ren Chang Jiu"],
    voice: { brightness: 65, warmth: 70, weight: 25, breathiness: 35, roughness: 10, vibrato: 55 },
    technique: ["vibrato", "soft onset", "slides", "straight tone"],
    delivery: ["legato", "intimate", "controlled", "restrained"],
    personality: ["sweet", "timeless"],
  },
  {
    id: "jj-lin", name: "JJ Lin", type: "Tenor",
    lang: "zh", low: "C3", high: "C5", tone: "bright", genres: ["Mandopop", "R&B", "Pop"],
    blurb: "Polished Mandopop tenor — clean falsetto, precise runs and big ballad climaxes.",
    songs: ["Jiang Nan", "Xiu Lian Ai Qing", "Bu Wei Shui Er Zuo De Ge", "Sha Shou", "Ta Shuo"],
    voice: { brightness: 65, warmth: 60, weight: 40, breathiness: 25, roughness: 10, vibrato: 55 },
    technique: ["falsetto", "runs", "vibrato", "belt"],
    delivery: ["dramatic", "precise", "sustained", "dynamic"],
    personality: ["polished", "soaring"],
  },
  {
    id: "gem", name: "G.E.M.", type: "Mezzo-soprano",
    lang: "zh", low: "G3", high: "E5", tone: "bright", genres: ["Mandopop", "Pop", "R&B"],
    blurb: "Powerhouse mezzo — huge belts, sky-high notes and total control.",
    songs: ["Guang Nian Zhi Wai", "Ni Ba Wo Guan Zui", "Nan Hai", "Bubble", "Xin Zhong De Ri Yue"],
    voice: { brightness: 70, warmth: 55, weight: 55, breathiness: 15, roughness: 15, vibrato: 70 },
    technique: ["belt", "runs", "vibrato", "falsetto"],
    delivery: ["dramatic", "powerful", "dynamic", "precise"],
    personality: ["powerful", "polished"],
  },
  {
    id: "a-mei", name: "A-Mei", type: "Mezzo-soprano",
    lang: "zh", low: "G3", high: "D5", tone: "warm", genres: ["Mandopop", "Pop", "Rock"],
    blurb: "Rock-soul mezzo — husky warmth and cathartic power.",
    songs: ["Ting Hai", "Jie Mei", "Ji De", "Lian Ai Cheng Shi", "San Tian San Ye"],
    voice: { brightness: 55, warmth: 65, weight: 60, breathiness: 25, roughness: 45, vibrato: 60 },
    technique: ["belt", "rasp", "vibrato", "slides"],
    delivery: ["powerful", "dramatic", "dynamic", "elastic"],
    personality: ["husky", "cathartic"],
  },
  {
    id: "faye-wong", name: "Faye Wong", type: "Soprano",
    lang: "zh", low: "A3", high: "E5", tone: "bright", genres: ["Mandopop", "Alternative", "Pop"],
    blurb: "Ethereal, floating soprano — airy, unhurried and cool as glass.",
    songs: ["Hong Dou", "Wo Yuan Yi", "Chuan Qi", "Meng Zhong Ren", "Kuang Lian"],
    voice: { brightness: 65, warmth: 50, weight: 25, breathiness: 55, roughness: 10, vibrato: 35 },
    technique: ["breathy", "straight tone", "soft onset", "slides"],
    delivery: ["legato", "understated", "intimate", "restrained"],
    personality: ["ethereal", "cool"],
  },
  {
    id: "regine-velasquez", name: "Regine Velasquez", type: "Soprano",
    lang: "tl", low: "G3", high: "E5", tone: "bright", genres: ["OPM", "Pop", "Ballad"],
    blurb: "Asia's Songbird — stratospheric belts and immaculate ballad control.",
    songs: ["Dadalhin", "Kailangan Ko'y Ikaw", "Pangako", "Araw Gabi", "Sana Maulit Muli"],
    voice: { brightness: 70, warmth: 55, weight: 60, breathiness: 10, roughness: 15, vibrato: 75 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["dramatic", "powerful", "sustained", "precise"],
    personality: ["soaring", "commanding"],
  },
  {
    id: "moira-dela-torre", name: "Moira Dela Torre", type: "Mezzo-soprano",
    lang: "tl", low: "G3", high: "D5", tone: "warm", genres: ["OPM", "Pop", "Folk"],
    blurb: "Whisper-soft OPM mezzo — breathy, tender and heartbreakingly close.",
    songs: ["Tagpuan", "Malaya", "Paubaya", "Ikaw at Ako", "Titibo-tibo"],
    voice: { brightness: 55, warmth: 65, weight: 25, breathiness: 70, roughness: 10, vibrato: 25 },
    technique: ["breathy", "soft onset", "straight tone", "slides"],
    delivery: ["intimate", "understated", "legato", "conversational"],
    personality: ["tender", "intimate"],
  },
  {
    id: "zack-tabudlo", name: "Zack Tabudlo", type: "Tenor",
    lang: "tl", low: "C3", high: "B4", tone: "warm", genres: ["OPM", "Pop", "R&B"],
    blurb: "Smooth, youthful OPM tenor — easy falsetto and instantly singable hooks.",
    songs: ["Binibini", "Habang Buhay", "Nangangamba", "Pano", "Give Me Your Forever"],
    voice: { brightness: 60, warmth: 60, weight: 35, breathiness: 40, roughness: 10, vibrato: 35 },
    technique: ["falsetto", "breathy", "soft onset", "runs"],
    delivery: ["legato", "rhythmic", "intimate", "controlled"],
    personality: ["smooth", "earnest"],
  },
  {
    id: "sarah-geronimo", name: "Sarah Geronimo", type: "Mezzo-soprano",
    lang: "tl", low: "G3", high: "E5", tone: "bright", genres: ["OPM", "Pop", "Dance"],
    blurb: "Bright, versatile Popstar Royalty — big ballads and slick dance-pop alike.",
    songs: ["Tala", "Forever's Not Enough", "Kilometro", "Ikot-Ikot", "Dati-Dati"],
    voice: { brightness: 70, warmth: 55, weight: 45, breathiness: 20, roughness: 15, vibrato: 60 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["dynamic", "precise", "dramatic", "rhythmic"],
    personality: ["versatile", "polished"],
  },
  {
    id: "gary-valenciano", name: "Gary Valenciano", type: "Tenor",
    lang: "tl", low: "C3", high: "B4", tone: "bright", genres: ["OPM", "Pop", "Gospel"],
    blurb: "Mr. Pure Energy — agile, soulful tenor with gospel fire.",
    songs: ["Sana Maulit Muli", "Natutulog Ba ang Diyos", "Warrior Is a Child", "Gaya ng Dati", "Hataw Na"],
    voice: { brightness: 65, warmth: 60, weight: 45, breathiness: 15, roughness: 20, vibrato: 60 },
    technique: ["runs", "vibrato", "belt", "scoops"],
    delivery: ["dynamic", "rhythmic", "dramatic", "elastic"],
    personality: ["energetic", "soulful"],
  },
  {
    id: "morissette", name: "Morissette", type: "Soprano",
    lang: "tl", low: "G3", high: "F5", tone: "bright", genres: ["OPM", "Pop", "R&B"],
    blurb: "Astonishing range — whistle notes, silky runs and fearless belts.",
    songs: ["Akin Ka Na Lang", "Throwback", "Phoenix", "Naririnig Mo Ba", "Diamante"],
    voice: { brightness: 75, warmth: 50, weight: 45, breathiness: 20, roughness: 10, vibrato: 70 },
    technique: ["belt", "runs", "falsetto", "vibrato"],
    delivery: ["precise", "dynamic", "dramatic", "powerful"],
    personality: ["virtuosic", "fearless"],
  },
  {
    id: "amr-diab", name: "Amr Diab", type: "Tenor",
    lang: "ar", low: "C3", high: "A4", tone: "warm", genres: ["Arabic Pop", "Pop", "Dance"],
    blurb: "The Mediterranean-pop king — smooth, breezy tenor with irresistible groove.",
    songs: ["Tamally Maak", "Nour El Ein", "Habibi Ya Nour El Ein", "Ya Ana Ya La", "El Leila"],
    voice: { brightness: 55, warmth: 65, weight: 45, breathiness: 35, roughness: 15, vibrato: 40 },
    technique: ["vibrato", "slides", "soft onset", "runs"],
    delivery: ["rhythmic", "legato", "controlled", "intimate"],
    personality: ["smooth", "breezy"],
  },
  {
    id: "nancy-ajram", name: "Nancy Ajram", type: "Soprano",
    lang: "ar", low: "A3", high: "D5", tone: "bright", genres: ["Arabic Pop", "Pop"],
    blurb: "Sweet, playful Lebanese pop soprano with light ornament and charm.",
    songs: ["Ah W Noss", "Ya Tabtab", "Akhasmak Ah", "Fi Hagat", "Ma Tegi Hena"],
    voice: { brightness: 65, warmth: 60, weight: 30, breathiness: 30, roughness: 10, vibrato: 45 },
    technique: ["vibrato", "runs", "soft onset", "slides"],
    delivery: ["rhythmic", "precise", "controlled", "conversational"],
    personality: ["playful", "sweet"],
  },
  {
    id: "fairuz", name: "Fairuz", type: "Alto",
    lang: "ar", low: "F3", high: "C5", tone: "warm", genres: ["Arabic", "Folk", "Classical"],
    blurb: "Lebanon's beloved alto — serene, silvery and profoundly dignified.",
    songs: ["Li Beirut", "Nassam Alayna El Hawa", "Kifak Inta", "Habaytak Bisayf", "Sanarjiou Yawman"],
    voice: { brightness: 55, warmth: 70, weight: 45, breathiness: 20, roughness: 10, vibrato: 50 },
    technique: ["vibrato", "straight tone", "slides", "soft onset"],
    delivery: ["legato", "restrained", "sustained", "controlled"],
    personality: ["serene", "dignified"],
  },
  {
    id: "elissa", name: "Elissa", type: "Mezzo-soprano",
    lang: "ar", low: "G3", high: "D5", tone: "warm", genres: ["Arabic Pop", "Ballad"],
    blurb: "Velvety Lebanese ballad mezzo — soft, romantic and quietly powerful.",
    songs: ["Ajmal Ihssas", "Aa Bali Habibi", "Halet Hob", "Ya Merayti", "Aayshalak"],
    voice: { brightness: 50, warmth: 70, weight: 40, breathiness: 45, roughness: 10, vibrato: 50 },
    technique: ["breathy", "vibrato", "soft onset", "slides"],
    delivery: ["legato", "intimate", "sustained", "dramatic"],
    personality: ["romantic", "velvety"],
  },
  {
    id: "tamer-hosny", name: "Tamer Hosny", type: "Tenor",
    lang: "ar", low: "C3", high: "A4", tone: "warm", genres: ["Arabic Pop", "Pop", "R&B"],
    blurb: "Egyptian pop heart-throb — soft, breathy tenor with R&B sway.",
    songs: ["Ya Bent El Eih", "Naseny Leh", "180 Daraga", "Kol Marra", "Arrab Kaman"],
    voice: { brightness: 55, warmth: 65, weight: 40, breathiness: 45, roughness: 15, vibrato: 35 },
    technique: ["breathy", "slides", "soft onset", "runs"],
    delivery: ["rhythmic", "intimate", "legato", "conversational"],
    personality: ["soft", "charming"],
  },
  {
    id: "umm-kulthum", name: "Umm Kulthum", type: "Alto",
    lang: "ar", low: "F3", high: "C5", tone: "dark", genres: ["Arabic", "Classical"],
    blurb: "The Star of the East — vast, commanding alto and hypnotic improvised ornament.",
    songs: ["Enta Omri", "Alf Leila wa Leila", "Fakkarouni", "Amal Hayati", "Al Atlal"],
    voice: { brightness: 45, warmth: 65, weight: 70, breathiness: 10, roughness: 25, vibrato: 70 },
    technique: ["vibrato", "runs", "belt", "slides"],
    delivery: ["dramatic", "powerful", "sustained", "elastic"],
    personality: ["commanding", "hypnotic"],
  },
];

function spotifyUrl(title, artist) {
  return "https://open.spotify.com/search/" + encodeURIComponent(title + " " + artist);
}

function youtubeUrl(title, artist) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(artist + " " + title);
}

function karaokeUrl(title, artist) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(artist + " " + title + " karaoke");
}

/*
 * Sing-with-friends catalogue.
 * DUETS: two written parts with approximate melodic ranges for each part.
 * GROUP_SONGS: sing-alongs with the approximate range of the main melody; in
 * a group everyone sings in whichever octave suits them, so matching allows
 * an octave shift.
 */
const DUETS = [
  { title: "Shallow", artists: "Bradley Cooper & Lady Gaga", parts: [{ name: "Bradley Cooper", low: "G2", high: "D4" }, { name: "Lady Gaga", low: "A3", high: "G5" }], genres: ["Pop", "Country"], lang: "en" },
  { title: "Die with a Smile", artists: "Bruno Mars & Lady Gaga", parts: [{ name: "Bruno Mars", low: "C3", high: "A4" }, { name: "Lady Gaga", low: "A3", high: "E5" }], genres: ["Pop", "R&B"], lang: "en" },
  { title: "Señorita", artists: "Shawn Mendes & Camila Cabello", parts: [{ name: "Shawn Mendes", low: "B2", high: "B4" }, { name: "Camila Cabello", low: "G3", high: "D5" }], genres: ["Pop"], lang: "en" },
  { title: "Islands in the Stream", artists: "Kenny Rogers & Dolly Parton", parts: [{ name: "Kenny Rogers", low: "G2", high: "D4" }, { name: "Dolly Parton", low: "G3", high: "D5" }], genres: ["Country", "Pop"], lang: "en" },
  { title: "Endless Love", artists: "Lionel Richie & Diana Ross", parts: [{ name: "Lionel Richie", low: "A2", high: "D4" }, { name: "Diana Ross", low: "A3", high: "C5" }], genres: ["Soul", "Pop"], lang: "en" },
  { title: "Don't Go Breaking My Heart", artists: "Elton John & Kiki Dee", parts: [{ name: "Elton John", low: "C3", high: "F4" }, { name: "Kiki Dee", low: "C4", high: "F5" }], genres: ["Pop"], lang: "en" },
  { title: "Lucky", artists: "Jason Mraz & Colbie Caillat", parts: [{ name: "Jason Mraz", low: "C3", high: "A4" }, { name: "Colbie Caillat", low: "G3", high: "D5" }], genres: ["Pop", "Folk"], lang: "en" },
  { title: "Say Something", artists: "A Great Big World & Christina Aguilera", parts: [{ name: "Ian Axel", low: "A2", high: "E4" }, { name: "Christina Aguilera", low: "E3", high: "B4" }], genres: ["Pop"], lang: "en" },
  { title: "Just Give Me a Reason", artists: "P!nk & Nate Ruess", parts: [{ name: "Nate Ruess", low: "B2", high: "B4" }, { name: "P!nk", low: "A3", high: "D5" }], genres: ["Pop"], lang: "en" },
  { title: "Somebody That I Used to Know", artists: "Gotye & Kimbra", parts: [{ name: "Gotye", low: "D3", high: "E4" }, { name: "Kimbra", low: "A3", high: "D5" }], genres: ["Alternative", "Pop"], lang: "en" },
  { title: "Under Pressure", artists: "Queen & David Bowie", parts: [{ name: "David Bowie", low: "G2", high: "G4" }, { name: "Freddie Mercury", low: "C3", high: "C5" }], genres: ["Rock"], lang: "en" },
  { title: "Ain't No Mountain High Enough", artists: "Marvin Gaye & Tammi Terrell", parts: [{ name: "Marvin Gaye", low: "C3", high: "G4" }, { name: "Tammi Terrell", low: "G3", high: "D5" }], genres: ["Soul"], lang: "en" },
  { title: "Up Where We Belong", artists: "Joe Cocker & Jennifer Warnes", parts: [{ name: "Joe Cocker", low: "G2", high: "D4" }, { name: "Jennifer Warnes", low: "G3", high: "D5" }], genres: ["Pop"], lang: "en" },
  { title: "A Whole New World", artists: "Peabo Bryson & Regina Belle", parts: [{ name: "Peabo Bryson", low: "D3", high: "G4" }, { name: "Regina Belle", low: "A3", high: "D5" }], genres: ["Pop", "Musical"], lang: "en" },
  { title: "Beauty and the Beast", artists: "Céline Dion & Peabo Bryson", parts: [{ name: "Peabo Bryson", low: "D3", high: "G4" }, { name: "Céline Dion", low: "A3", high: "D5" }], genres: ["Pop", "Musical"], lang: "en" },
  { title: "Rewrite the Stars", artists: "Zac Efron & Zendaya", parts: [{ name: "Zac Efron", low: "A2", high: "A4" }, { name: "Zendaya", low: "A3", high: "C5" }], genres: ["Pop", "Musical"], lang: "en" },
  { title: "Perfect Duet", artists: "Ed Sheeran & Beyoncé", parts: [{ name: "Ed Sheeran", low: "A2", high: "B4" }, { name: "Beyoncé", low: "G3", high: "E5" }], genres: ["Pop"], lang: "en" },
  { title: "Stay", artists: "Rihanna & Mikky Ekko", parts: [{ name: "Mikky Ekko", low: "A2", high: "A4" }, { name: "Rihanna", low: "G3", high: "C5" }], genres: ["Pop"], lang: "en" },
  { title: "Everything Has Changed", artists: "Taylor Swift & Ed Sheeran", parts: [{ name: "Ed Sheeran", low: "A2", high: "A4" }, { name: "Taylor Swift", low: "G3", high: "D5" }], genres: ["Pop"], lang: "en" },
  { title: "Summer Nights", artists: "John Travolta & Olivia Newton-John", parts: [{ name: "John Travolta", low: "B2", high: "E4" }, { name: "Olivia Newton-John", low: "B3", high: "E5" }], genres: ["Musical", "Pop"], lang: "en" },
  { title: "You're the One That I Want", artists: "John Travolta & Olivia Newton-John", parts: [{ name: "John Travolta", low: "B2", high: "E4" }, { name: "Olivia Newton-John", low: "B3", high: "E5" }], genres: ["Musical", "Pop"], lang: "en" },
  { title: "I Got You Babe", artists: "Sonny & Cher", parts: [{ name: "Sonny Bono", low: "G2", high: "D4" }, { name: "Cher", low: "G3", high: "D5" }], genres: ["Pop"], lang: "en" },
  { title: "Almost Is Never Enough", artists: "Ariana Grande & Nathan Sykes", parts: [{ name: "Nathan Sykes", low: "C3", high: "A4" }, { name: "Ariana Grande", low: "G3", high: "E5" }], genres: ["Pop", "R&B"], lang: "en" },
  { title: "Leather and Lace", artists: "Stevie Nicks & Don Henley", parts: [{ name: "Don Henley", low: "B2", high: "D4" }, { name: "Stevie Nicks", low: "A3", high: "D5" }], genres: ["Rock"], lang: "en" },
  { title: "The Prayer", artists: "Céline Dion & Andrea Bocelli", parts: [{ name: "Andrea Bocelli", low: "C3", high: "A4" }, { name: "Céline Dion", low: "A3", high: "D5" }], genres: ["Pop", "Classical"], lang: "en" },
  { title: "Broken Strings", artists: "James Morrison & Nelly Furtado", parts: [{ name: "James Morrison", low: "C3", high: "A4" }, { name: "Nelly Furtado", low: "G3", high: "C5" }], genres: ["Pop"], lang: "en" },
  { title: "Cruisin'", artists: "Huey Lewis & Gwyneth Paltrow", parts: [{ name: "Huey Lewis", low: "G2", high: "E4" }, { name: "Gwyneth Paltrow", low: "G3", high: "E5" }], genres: ["Pop"], lang: "en" },
  { title: "Somethin' Stupid", artists: "Robbie Williams & Nicole Kidman", parts: [{ name: "Robbie Williams", low: "A2", high: "D4" }, { name: "Nicole Kidman", low: "A3", high: "D5" }], genres: ["Pop", "Swing"], lang: "en" },
  { title: "Fairytale of New York", artists: "The Pogues & Kirsty MacColl", parts: [{ name: "Shane MacGowan", low: "G2", high: "D4" }, { name: "Kirsty MacColl", low: "G3", high: "D5" }], genres: ["Folk", "Rock"], lang: "en" },
  { title: "Beneath Your Beautiful", artists: "Labrinth & Emeli Sandé", parts: [{ name: "Labrinth", low: "C3", high: "A4" }, { name: "Emeli Sandé", low: "A3", high: "E5" }], genres: ["Pop", "R&B"], lang: "en" },
  { title: "Love Is an Open Door", artists: "Kristen Bell & Santino Fontana", parts: [{ name: "Hans", low: "A2", high: "E4" }, { name: "Anna", low: "A3", high: "D5" }], genres: ["Musical", "Pop"], lang: "en" },
  { title: "Nothing's Gonna Stop Us Now", artists: "Starship", parts: [{ name: "Mickey Thomas", low: "A2", high: "G4" }, { name: "Grace Slick", low: "A3", high: "D5" }], genres: ["Rock", "Pop"], lang: "en" },
  { title: "Tonight, I Celebrate My Love", artists: "Peabo Bryson & Roberta Flack", parts: [{ name: "Peabo Bryson", low: "C3", high: "G4" }, { name: "Roberta Flack", low: "G3", high: "D5" }], genres: ["Soul"], lang: "en" },
  { title: "Falling Slowly", artists: "Glen Hansard & Markéta Irglová", parts: [{ name: "Glen Hansard", low: "C3", high: "A4" }, { name: "Markéta Irglová", low: "G3", high: "D5" }], genres: ["Folk"], lang: "en" },
  { title: "Unforgettable", artists: "Nat King Cole & Natalie Cole", parts: [{ name: "Nat King Cole", low: "G2", high: "D4" }, { name: "Natalie Cole", low: "G3", high: "D5" }], genres: ["Jazz"], lang: "en" },
  { title: "I Had Some Help", artists: "Post Malone & Morgan Wallen", parts: [{ name: "Post Malone", low: "G2", high: "G4" }, { name: "Morgan Wallen", low: "A2", high: "A4" }], genres: ["Country", "Pop"], lang: "en" },
  { title: "La Bicicleta", artists: "Carlos Vives & Shakira", parts: [{ name: "Carlos Vives", low: "B2", high: "A4" }, { name: "Shakira", low: "G3", high: "D5" }], genres: ["Latin", "Pop"], lang: "es" },
  { title: "Échame la Culpa", artists: "Luis Fonsi & Demi Lovato", parts: [{ name: "Luis Fonsi", low: "C3", high: "A4" }, { name: "Demi Lovato", low: "A3", high: "E5" }], genres: ["Latin", "Pop"], lang: "es" },
  { title: "Chantaje", artists: "Shakira & Maluma", parts: [{ name: "Maluma", low: "B2", high: "G4" }, { name: "Shakira", low: "G3", high: "C5" }], genres: ["Reggaeton", "Pop"], lang: "es" },
  { title: "Por Primera Vez", artists: "Camilo & Evaluna Montaner", parts: [{ name: "Camilo", low: "C3", high: "A4" }, { name: "Evaluna Montaner", low: "A3", high: "D5" }], genres: ["Latin", "Pop"], lang: "es" },
  { title: "Some", artists: "Soyou & Junggigo", parts: [{ name: "Junggigo", low: "C3", high: "A4" }, { name: "Soyou", low: "A3", high: "D5" }], genres: ["K-Pop", "R&B"], lang: "ko" },
  { title: "Everytime", artists: "Chen & Punch", parts: [{ name: "Chen", low: "C3", high: "B4" }, { name: "Punch", low: "A3", high: "D5" }], genres: ["K-Pop", "Ballad"], lang: "ko" },
  { title: "Nagging", artists: "IU & Lim Seulong", parts: [{ name: "Lim Seulong", low: "C3", high: "A4" }, { name: "IU", low: "A3", high: "D5" }], genres: ["K-Pop"], lang: "ko" },
  { title: "Suraj Hua Maddham", artists: "Sonu Nigam & Alka Yagnik", parts: [{ name: "Sonu Nigam", low: "C3", high: "A4" }, { name: "Alka Yagnik", low: "G3", high: "D5" }], genres: ["Bollywood"], lang: "hi" },
  { title: "Gerua", artists: "Arijit Singh & Antara Mitra", parts: [{ name: "Arijit Singh", low: "B2", high: "A4" }, { name: "Antara Mitra", low: "G3", high: "D5" }], genres: ["Bollywood"], lang: "hi" },
  { title: "Kabira", artists: "Tochi Raina & Rekha Bhardwaj", parts: [{ name: "Tochi Raina", low: "B2", high: "A4" }, { name: "Rekha Bhardwaj", low: "G3", high: "C5" }], genres: ["Bollywood"], lang: "hi" },
  { title: "Sous le vent", artists: "Garou & Céline Dion", parts: [{ name: "Garou", low: "G2", high: "G4" }, { name: "Céline Dion", low: "A3", high: "D5" }], genres: ["Pop", "Chanson"], lang: "fr" },
  { title: "Tu es mon autre", artists: "Lara Fabian & Maurane", parts: [{ name: "Maurane", low: "G3", high: "C5" }, { name: "Lara Fabian", low: "A3", high: "E5" }], genres: ["Chanson", "Pop"], lang: "fr" },
  { title: "Evidências", artists: "Chitãozinho & Xororó", parts: [{ name: "Chitãozinho", low: "B2", high: "B4" }, { name: "Xororó", low: "B2", high: "B4" }], genres: ["Sertanejo"], lang: "pt" },
  { title: "Wu Ding", artists: "Jacky Wu & Landy Wen", parts: [{ name: "Jacky Wu", low: "B2", high: "A4" }, { name: "Landy Wen", low: "G3", high: "D5" }], genres: ["Mandopop"], lang: "zh" },
  { title: "Ikaw at Ako", artists: "Moira Dela Torre & Jason Marvin", parts: [{ name: "Jason Marvin", low: "C3", high: "A4" }, { name: "Moira Dela Torre", low: "G3", high: "D5" }], genres: ["OPM"], lang: "tl" },
];

const GROUP_SONGS = [
  { title: "Sweet Caroline", artist: "Neil Diamond", low: "B2", high: "D4", genres: ["Pop"], lang: "en" },
  { title: "Hey Jude", artist: "The Beatles", low: "C3", high: "F4", genres: ["Rock", "Pop"], lang: "en" },
  { title: "Don't Stop Believin'", artist: "Journey", low: "E3", high: "B4", genres: ["Rock"], lang: "en" },
  { title: "Bohemian Rhapsody", artist: "Queen", low: "G3", high: "D5", genres: ["Rock"], lang: "en" },
  { title: "Wonderwall", artist: "Oasis", low: "F#3", high: "A4", genres: ["Rock"], lang: "en" },
  { title: "Mr. Brightside", artist: "The Killers", low: "C#3", high: "F#4", genres: ["Rock"], lang: "en" },
  { title: "Dancing Queen", artist: "ABBA", low: "A3", high: "D5", genres: ["Pop", "Disco"], lang: "en" },
  { title: "Take Me Home, Country Roads", artist: "John Denver", low: "A2", high: "D4", genres: ["Country", "Folk"], lang: "en" },
  { title: "Wannabe", artist: "Spice Girls", low: "G3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Africa", artist: "Toto", low: "G3", high: "C5", genres: ["Pop", "Rock"], lang: "en" },
  { title: "I Want It That Way", artist: "Backstreet Boys", low: "A2", high: "A4", genres: ["Pop"], lang: "en" },
  { title: "Riptide", artist: "Vance Joy", low: "C#3", high: "E4", genres: ["Folk", "Pop"], lang: "en" },
  { title: "Stand by Me", artist: "Ben E. King", low: "A2", high: "D4", genres: ["Soul"], lang: "en" },
  { title: "Lean on Me", artist: "Bill Withers", low: "C3", high: "D4", genres: ["Soul"], lang: "en" },
  { title: "Count on Me", artist: "Bruno Mars", low: "C3", high: "F4", genres: ["Pop"], lang: "en" },
  { title: "We Are the Champions", artist: "Queen", low: "F3", high: "C5", genres: ["Rock"], lang: "en" },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", low: "E3", high: "E5", genres: ["Rock"], lang: "en" },
  { title: "Hallelujah", artist: "Leonard Cohen", low: "C3", high: "E4", genres: ["Folk"], lang: "en" },
  { title: "Let It Be", artist: "The Beatles", low: "C3", high: "G4", genres: ["Rock", "Pop"], lang: "en" },
  { title: "Valerie", artist: "Amy Winehouse", low: "D3", high: "B4", genres: ["Soul", "Pop"], lang: "en" },
  { title: "Perfect", artist: "Ed Sheeran", low: "A2", high: "B4", genres: ["Pop"], lang: "en" },
  { title: "Shut Up and Dance", artist: "Walk the Moon", low: "D3", high: "B4", genres: ["Pop", "Rock"], lang: "en" },
  { title: "Yellow", artist: "Coldplay", low: "B2", high: "E4", genres: ["Rock", "Alternative"], lang: "en" },
  { title: "Uptown Funk", artist: "Bruno Mars", low: "D3", high: "B4", genres: ["Funk", "Pop"], lang: "en" },
  { title: "Shake It Off", artist: "Taylor Swift", low: "G3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Rolling in the Deep", artist: "Adele", low: "B3", high: "D5", genres: ["Pop", "Soul"], lang: "en" },
  { title: "Piano Man", artist: "Billy Joel", low: "C3", high: "E4", genres: ["Pop"], lang: "en" },
  { title: "Ho Hey", artist: "The Lumineers", low: "B2", high: "E4", genres: ["Folk"], lang: "en" },
  { title: "Viva la Vida", artist: "Coldplay", low: "F3", high: "C5", genres: ["Rock"], lang: "en" },
  { title: "Torn", artist: "Natalie Imbruglia", low: "E3", high: "B4", genres: ["Pop"], lang: "en" },
  { title: "Flowers", artist: "Miley Cyrus", low: "A3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "As It Was", artist: "Harry Styles", low: "C#3", high: "A4", genres: ["Pop"], lang: "en" },
  { title: "Blinding Lights", artist: "The Weeknd", low: "F3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Espresso", artist: "Sabrina Carpenter", low: "A3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Birds of a Feather", artist: "Billie Eilish", low: "A3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Beautiful Things", artist: "Benson Boone", low: "E3", high: "B4", genres: ["Pop"], lang: "en" },
  { title: "Stick Season", artist: "Noah Kahan", low: "B2", high: "A4", genres: ["Folk", "Pop"], lang: "en" },
  { title: "Lose Control", artist: "Teddy Swims", low: "F3", high: "C5", genres: ["Soul", "Pop"], lang: "en" },
  { title: "Good Luck, Babe!", artist: "Chappell Roan", low: "G3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Angels", artist: "Robbie Williams", low: "A2", high: "A4", genres: ["Pop"], lang: "en" },
  { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", low: "A3", high: "D5", genres: ["Pop"], lang: "en" },
  { title: "Three Little Birds", artist: "Bob Marley", low: "C3", high: "C4", genres: ["Reggae"], lang: "en" },
  { title: "Say You Won't Let Go", artist: "James Arthur", low: "A2", high: "B4", genres: ["Pop"], lang: "en" },
  { title: "Someone You Loved", artist: "Lewis Capaldi", low: "C3", high: "B4", genres: ["Pop"], lang: "en" },
  { title: "Despacito", artist: "Luis Fonsi", low: "B2", high: "B4", genres: ["Latin", "Reggaeton"], lang: "es" },
  { title: "Vivir Mi Vida", artist: "Marc Anthony", low: "A2", high: "A4", genres: ["Latin", "Salsa"], lang: "es" },
  { title: "La Camisa Negra", artist: "Juanes", low: "A2", high: "A4", genres: ["Latin", "Rock"], lang: "es" },
  { title: "Bailando", artist: "Enrique Iglesias", low: "A2", high: "G4", genres: ["Latin", "Pop"], lang: "es" },
  { title: "Color Esperanza", artist: "Diego Torres", low: "B2", high: "A4", genres: ["Latin", "Pop"], lang: "es" },
  { title: "Cielito Lindo", artist: "Traditional", low: "C3", high: "E4", genres: ["Latin", "Folk"], lang: "es" },
  { title: "Me Gustas Tú", artist: "Manu Chao", low: "C3", high: "D4", genres: ["Latin", "Alternative"], lang: "es" },
  { title: "Bésame Mucho", artist: "Consuelo Velázquez", low: "G3", high: "C5", genres: ["Latin", "Bolero"], lang: "es" },
  { title: "Spring Day", artist: "BTS", low: "B2", high: "A4", genres: ["K-Pop"], lang: "ko" },
  { title: "Through the Night", artist: "IU", low: "A3", high: "D5", genres: ["K-Pop", "Folk"], lang: "ko" },
  { title: "Cheer Up", artist: "TWICE", low: "A3", high: "D5", genres: ["K-Pop"], lang: "ko" },
  { title: "Gangnam Style", artist: "PSY", low: "C3", high: "C4", genres: ["K-Pop", "Dance"], lang: "ko" },
  { title: "Love Scenario", artist: "iKON", low: "C3", high: "A4", genres: ["K-Pop"], lang: "ko" },
  { title: "Cherry Blossom Ending", artist: "Busker Busker", low: "A2", high: "A4", genres: ["K-Pop", "Folk"], lang: "ko" },
  { title: "Lemon", artist: "Kenshi Yonezu", low: "A2", high: "A4", genres: ["J-Pop"], lang: "ja" },
  { title: "Pretender", artist: "Official HIGE DANdism", low: "C3", high: "C5", genres: ["J-Pop"], lang: "ja" },
  { title: "Idol", artist: "YOASOBI", low: "A3", high: "E5", genres: ["J-Pop"], lang: "ja" },
  { title: "Sakura", artist: "Naotaro Moriyama", low: "A2", high: "A4", genres: ["J-Pop", "Folk"], lang: "ja" },
  { title: "Ue wo Muite Arukou", artist: "Kyu Sakamoto", low: "C3", high: "D4", genres: ["J-Pop", "Classic"], lang: "ja" },
  { title: "Sekai ni Hitotsu Dake no Hana", artist: "SMAP", low: "B2", high: "A4", genres: ["J-Pop"], lang: "ja" },
  { title: "First Love", artist: "Hikaru Utada", low: "G3", high: "D5", genres: ["J-Pop", "R&B"], lang: "ja" },
  { title: "Kal Ho Naa Ho", artist: "Sonu Nigam", low: "C3", high: "B4", genres: ["Bollywood"], lang: "hi" },
  { title: "Tum Hi Ho", artist: "Arijit Singh", low: "B2", high: "A4", genres: ["Bollywood"], lang: "hi" },
  { title: "Kesariya", artist: "Arijit Singh", low: "B2", high: "G4", genres: ["Bollywood"], lang: "hi" },
  { title: "Chaiyya Chaiyya", artist: "Sukhwinder Singh", low: "C3", high: "B4", genres: ["Bollywood"], lang: "hi" },
  { title: "Pal Pal Dil Ke Paas", artist: "Kishore Kumar", low: "G2", high: "G4", genres: ["Bollywood"], lang: "hi" },
  { title: "Jai Ho", artist: "A. R. Rahman", low: "C3", high: "A4", genres: ["Bollywood"], lang: "hi" },
  { title: "Kabira", artist: "Tochi Raina & Rekha Bhardwaj", low: "B2", high: "A4", genres: ["Bollywood"], lang: "hi" },
  { title: "Je veux", artist: "Zaz", low: "G3", high: "D5", genres: ["Chanson", "Jazz"], lang: "fr" },
  { title: "Alors on danse", artist: "Stromae", low: "A2", high: "G4", genres: ["Pop", "Electronic"], lang: "fr" },
  { title: "La Vie en rose", artist: "Édith Piaf", low: "G3", high: "D5", genres: ["Chanson"], lang: "fr" },
  { title: "Les Champs-Élysées", artist: "Joe Dassin", low: "A2", high: "A4", genres: ["Chanson", "Pop"], lang: "fr" },
  { title: "Papaoutai", artist: "Stromae", low: "A2", high: "A4", genres: ["Pop"], lang: "fr" },
  { title: "Dernière danse", artist: "Indila", low: "A3", high: "D5", genres: ["Pop"], lang: "fr" },
  { title: "Je te promets", artist: "Johnny Hallyday", low: "A2", high: "A4", genres: ["Rock", "Chanson"], lang: "fr" },
  { title: "Garota de Ipanema", artist: "Tom Jobim", low: "C3", high: "D4", genres: ["Bossa Nova"], lang: "pt" },
  { title: "Ai Se Eu Te Pego", artist: "Michel Teló", low: "B2", high: "A4", genres: ["Sertanejo", "Pop"], lang: "pt" },
  { title: "Evidências", artist: "Chitãozinho & Xororó", low: "B2", high: "B4", genres: ["Sertanejo"], lang: "pt" },
  { title: "Águas de Março", artist: "Elis Regina & Tom Jobim", low: "G3", high: "D5", genres: ["MPB"], lang: "pt" },
  { title: "Trem-Bala", artist: "Ana Vilela", low: "A3", high: "D5", genres: ["MPB", "Pop"], lang: "pt" },
  { title: "Aquarela", artist: "Toquinho", low: "C3", high: "D4", genres: ["MPB"], lang: "pt" },
  { title: "Envolver", artist: "Anitta", low: "G3", high: "C5", genres: ["Funk", "Pop"], lang: "pt" },
  { title: "Peng You", artist: "Emil Chau", low: "A2", high: "A4", genres: ["Mandopop"], lang: "zh" },
  { title: "Yue Liang Dai Biao Wo De Xin", artist: "Teresa Teng", low: "A3", high: "D5", genres: ["Mandopop"], lang: "zh" },
  { title: "Tong Hua", artist: "Michael Wong", low: "B2", high: "A4", genres: ["Mandopop"], lang: "zh" },
  { title: "Hou Lai", artist: "Rene Liu", low: "G3", high: "C5", genres: ["Mandopop"], lang: "zh" },
  { title: "Qing Hua Ci", artist: "Jay Chou", low: "B2", high: "A4", genres: ["Mandopop"], lang: "zh" },
  { title: "Xiao Xing Yun", artist: "Hebe Tien", low: "A3", high: "E5", genres: ["Mandopop"], lang: "zh" },
  { title: "Ni Yao De Ai", artist: "Penny Tai", low: "G3", high: "D5", genres: ["Mandopop"], lang: "zh" },
  { title: "Tadhana", artist: "Up Dharma Down", low: "A3", high: "D5", genres: ["OPM"], lang: "tl" },
  { title: "Pare Ko", artist: "Eraserheads", low: "A2", high: "A4", genres: ["OPM", "Rock"], lang: "tl" },
  { title: "Ang Huling El Bimbo", artist: "Eraserheads", low: "B2", high: "B4", genres: ["OPM", "Rock"], lang: "tl" },
  { title: "Kathang Isip", artist: "Ben&Ben", low: "B2", high: "A4", genres: ["OPM", "Folk"], lang: "tl" },
  { title: "Hanggang Kailan", artist: "Orange & Lemons", low: "C3", high: "A4", genres: ["OPM"], lang: "tl" },
  { title: "Ikaw", artist: "Yeng Constantino", low: "G3", high: "D5", genres: ["OPM"], lang: "tl" },
  { title: "Buwan", artist: "Juan Karlos", low: "C3", high: "C5", genres: ["OPM"], lang: "tl" },
  { title: "Tamally Maak", artist: "Amr Diab", low: "C3", high: "A4", genres: ["Arabic Pop"], lang: "ar" },
  { title: "Ah W Noss", artist: "Nancy Ajram", low: "A3", high: "D5", genres: ["Arabic Pop"], lang: "ar" },
  { title: "Habibi Ya Nour El Ein", artist: "Amr Diab", low: "C3", high: "G4", genres: ["Arabic Pop"], lang: "ar" },
  { title: "Li Beirut", artist: "Fairuz", low: "F3", high: "C5", genres: ["Arabic"], lang: "ar" },
  { title: "3 Daqat", artist: "Abu & Yousra", low: "B2", high: "A4", genres: ["Arabic Pop"], lang: "ar" },
  { title: "Ya Rayah", artist: "Rachid Taha", low: "A2", high: "A4", genres: ["Arabic", "Raï"], lang: "ar" },
  { title: "Enta Omri", artist: "Umm Kulthum", low: "F3", high: "C5", genres: ["Arabic", "Classical"], lang: "ar" },
];

const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "es", label: "Español" },
  { code: "ko", label: "한국어" },
  { code: "ja", label: "日本語" },
  { code: "hi", label: "हिन्दी" },
  { code: "fr", label: "Français" },
  { code: "pt", label: "Português" },
  { code: "zh", label: "中文" },
  { code: "tl", label: "Tagalog" },
  { code: "ar", label: "العربية" },
];

function languageLabel(code) {
  const l = LANGUAGES.find((x) => x.code === code);
  return l ? l.label : "any language";
}

// Filter a catalogue by language, falling back to everything when a language
// has too few entries to be useful.
function byLanguage(list, lang, minimum) {
  if (!lang || lang === "any") return { list, fellBack: false };
  const filtered = list.filter((x) => x.lang === lang);
  return filtered.length >= minimum ? { list: filtered, fellBack: false } : { list, fellBack: true };
}
