"use strict";

/*
 * Curated singer dataset used for matching.
 *
 * low/high are approximate, commonly-cited *comfortable* singing ranges (not
 * extreme recorded ranges), which suits matching against a short sung line.
 *
 * voice.*     0–100 curated perceptual ratings (brightness, warmth, weight,
 *             breathiness, roughness, vibrato strength). These are human-style
 *             perceptual estimates, not acoustic measurements, and are compared
 *             only against the user's *derived* perceptual scores.
 * technique   how the singer uses the voice (shared vocabulary with engine.js):
 *             vibrato, straight tone, breathy, rasp, belt, falsetto, runs,
 *             scoops, slides, soft onset, firm onset, vocal fry.
 * delivery    performance style: legato, flowing, conversational, clipped,
 *             sustained, dynamic, understated, controlled, dramatic, rhythmic,
 *             behind-beat, precise, intimate, elastic, restrained, powerful.
 * personality derived descriptor tags, never used for similarity.
 * genres      musical style — kept separate from acoustic similarity.
 */
const SINGERS = [
  {
    id: "freddie-mercury", name: "Freddie Mercury", type: "Tenor",
    low: "F2", high: "F5", tone: "bright", genres: ["Rock", "Pop"],
    blurb: "Queen's frontman — famous for a huge range, raw power and theatrical delivery.",
    songs: ["Somebody to Love", "Don't Stop Me Now", "Love of My Life", "Bohemian Rhapsody", "We Are the Champions"],
    voice: { brightness: 70, warmth: 55, weight: 60, breathiness: 15, roughness: 40, vibrato: 80 },
    technique: ["vibrato", "belt", "rasp", "slides"],
    delivery: ["dramatic", "dynamic", "precise", "sustained"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "adele", name: "Adele", type: "Mezzo-soprano",
    low: "C3", high: "C5", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Rich, emotive mezzo with a warm lower register and powerful belts.",
    songs: ["Someone Like You", "Rolling in the Deep", "Easy on Me", "Hello", "When We Were Young"],
    voice: { brightness: 35, warmth: 70, weight: 70, breathiness: 25, roughness: 30, vibrato: 65 },
    technique: ["belt", "vibrato", "slides"],
    delivery: ["dramatic", "sustained", "dynamic", "legato"],
    personality: ["soulful", "commanding"],
  },
  {
    id: "ed-sheeran", name: "Ed Sheeran", type: "Tenor",
    low: "A2", high: "B4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Soft, breathy tenor built for intimate, melodic pop and acoustic songs.",
    songs: ["Perfect", "Thinking Out Loud", "Photograph", "Shape of You", "Shivers"],
    voice: { brightness: 55, warmth: 60, weight: 35, breathiness: 55, roughness: 15, vibrato: 30 },
    technique: ["breathy", "soft onset", "straight tone", "runs"],
    delivery: ["conversational", "rhythmic", "intimate", "legato"],
    personality: ["intimate", "conversational"],
  },
  {
    id: "beyonce", name: "Beyoncé", type: "Mezzo-soprano",
    low: "G3", high: "E5", tone: "bright", genres: ["R&B", "Pop"],
    blurb: "Agile, powerful mezzo with dazzling runs and precise control.",
    songs: ["Halo", "Love on Top", "If I Were a Boy", "Crazy in Love", "Texas Hold 'Em"],
    voice: { brightness: 65, warmth: 60, weight: 70, breathiness: 15, roughness: 20, vibrato: 70 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["precise", "powerful", "dynamic", "rhythmic"],
    personality: ["polished", "commanding"],
  },
  {
    id: "whitney-houston", name: "Whitney Houston", type: "Soprano",
    low: "C3", high: "C6", tone: "bright", genres: ["Pop", "R&B", "Gospel"],
    blurb: "One of the great pop voices — soaring belts and gospel-rooted phrasing.",
    songs: ["I Will Always Love You", "I Wanna Dance with Somebody", "Greatest Love of All", "How Will I Know", "I Have Nothing"],
    voice: { brightness: 70, warmth: 60, weight: 75, breathiness: 10, roughness: 15, vibrato: 85 },
    technique: ["belt", "vibrato", "runs", "slides"],
    delivery: ["powerful", "dramatic", "sustained", "precise"],
    personality: ["soaring", "polished"],
  },
  {
    id: "sam-smith", name: "Sam Smith", type: "Tenor",
    low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Silky tenor with an effortless falsetto and emotional delivery.",
    songs: ["Stay with Me", "Too Good at Goodbyes", "Lay Me Down", "Unholy", "I'm Not the Only One"],
    voice: { brightness: 55, warmth: 65, weight: 40, breathiness: 40, roughness: 15, vibrato: 70 },
    technique: ["falsetto", "vibrato", "runs", "soft onset"],
    delivery: ["legato", "sustained", "dramatic", "intimate"],
    personality: ["vulnerable", "soulful"],
  },
  {
    id: "ariana-grande", name: "Ariana Grande", type: "Soprano",
    low: "G3", high: "E6", tone: "bright", genres: ["Pop", "R&B"],
    blurb: "Light lyric soprano with a famous whistle register and nimble runs.",
    songs: ["Into You", "No Tears Left to Cry", "POV", "7 rings", "we can't be friends (wait for your love)"],
    voice: { brightness: 75, warmth: 45, weight: 30, breathiness: 35, roughness: 10, vibrato: 60 },
    technique: ["runs", "falsetto", "vibrato", "breathy"],
    delivery: ["precise", "legato", "rhythmic", "controlled"],
    personality: ["crystalline", "polished"],
  },
  {
    id: "bruno-mars", name: "Bruno Mars", type: "Tenor",
    low: "C3", high: "C5", tone: "bright", genres: ["Pop", "Funk", "R&B"],
    blurb: "Versatile retro-flavoured tenor — smooth, punchy and playful.",
    songs: ["When I Was Your Man", "Just the Way You Are", "Grenade", "Die with a Smile", "Leave the Door Open"],
    voice: { brightness: 65, warmth: 60, weight: 50, breathiness: 15, roughness: 25, vibrato: 60 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["rhythmic", "precise", "dynamic", "elastic"],
    personality: ["playful", "polished"],
  },
  {
    id: "frank-sinatra", name: "Frank Sinatra", type: "Baritone",
    low: "G2", high: "G4", tone: "warm", genres: ["Jazz", "Swing"],
    blurb: "The definitive crooner — relaxed phrasing and a velvety baritone.",
    songs: ["Fly Me to the Moon", "My Way", "Come Fly with Me", "The Way You Look Tonight", "New York, New York"],
    voice: { brightness: 45, warmth: 75, weight: 60, breathiness: 15, roughness: 15, vibrato: 55 },
    technique: ["vibrato", "slides", "firm onset"],
    delivery: ["legato", "conversational", "behind-beat", "controlled"],
    personality: ["smooth", "conversational"],
  },
  {
    id: "johnny-cash", name: "Johnny Cash", type: "Bass-baritone",
    low: "E2", high: "E4", tone: "dark", genres: ["Country", "Folk"],
    blurb: "Deep, steady bass-baritone with a storyteller's gravitas.",
    songs: ["Ring of Fire", "I Walk the Line", "Hurt", "Folsom Prison Blues", "A Boy Named Sue"],
    voice: { brightness: 25, warmth: 60, weight: 80, breathiness: 20, roughness: 45, vibrato: 20 },
    technique: ["straight tone", "firm onset", "vocal fry"],
    delivery: ["conversational", "restrained", "controlled"],
    personality: ["earthy", "restrained"],
  },
  {
    id: "barry-white", name: "Barry White", type: "Bass",
    low: "C2", high: "C4", tone: "dark", genres: ["Soul", "R&B", "Disco"],
    blurb: "Legendary low voice — smooth, resonant and unmistakably deep.",
    songs: ["Can't Get Enough of Your Love, Babe", "You're the First, the Last, My Everything", "Never, Never Gonna Give Ya Up", "Let the Music Play", "Practice What You Preach"],
    voice: { brightness: 15, warmth: 85, weight: 95, breathiness: 30, roughness: 30, vibrato: 35 },
    technique: ["straight tone", "soft onset", "vocal fry"],
    delivery: ["intimate", "legato", "sustained", "restrained"],
    personality: ["sensual", "smooth"],
  },
  {
    id: "amy-winehouse", name: "Amy Winehouse", type: "Contralto",
    low: "D3", high: "D5", tone: "dark", genres: ["Soul", "Jazz", "R&B"],
    blurb: "Smoky contralto steeped in jazz — expressive, raw and instantly recognisable.",
    songs: ["Back to Black", "Valerie", "Tears Dry on Their Own", "Rehab", "Love Is a Losing Game"],
    voice: { brightness: 35, warmth: 65, weight: 55, breathiness: 25, roughness: 55, vibrato: 45 },
    technique: ["rasp", "slides", "scoops", "runs"],
    delivery: ["behind-beat", "conversational", "elastic", "dramatic"],
    personality: ["smoky", "raw"],
  },
  {
    id: "tracy-chapman", name: "Tracy Chapman", type: "Contralto",
    low: "F3", high: "C5", tone: "warm", genres: ["Folk", "Rock"],
    blurb: "Warm, grounded contralto with an honest folk storyteller's tone.",
    songs: ["Fast Car", "Give Me One Reason", "Baby Can I Hold You", "Talkin' Bout a Revolution", "The Promise"],
    voice: { brightness: 40, warmth: 75, weight: 60, breathiness: 20, roughness: 25, vibrato: 35 },
    technique: ["straight tone", "firm onset", "slides"],
    delivery: ["conversational", "legato", "restrained", "controlled"],
    personality: ["earthy", "honest"],
  },
  {
    id: "norah-jones", name: "Norah Jones", type: "Contralto",
    low: "G3", high: "C5", tone: "warm", genres: ["Jazz", "Pop"],
    blurb: "Hushed, jazzy voice — mellow, intimate and effortlessly smooth.",
    songs: ["Don't Know Why", "Come Away with Me", "Sunrise", "Turn Me On", "Chasing Pirates"],
    voice: { brightness: 40, warmth: 80, weight: 35, breathiness: 55, roughness: 10, vibrato: 30 },
    technique: ["breathy", "soft onset", "straight tone", "slides"],
    delivery: ["intimate", "behind-beat", "legato", "understated"],
    personality: ["dreamy", "intimate"],
  },
  {
    id: "michael-buble", name: "Michael Bublé", type: "Baritone",
    low: "A2", high: "A4", tone: "warm", genres: ["Jazz", "Swing", "Pop"],
    blurb: "Modern crooner — polished baritone with a big-band swagger.",
    songs: ["Feeling Good", "Haven't Met You Yet", "Home", "Everything", "Sway"],
    voice: { brightness: 55, warmth: 70, weight: 55, breathiness: 15, roughness: 15, vibrato: 65 },
    technique: ["vibrato", "belt", "slides"],
    delivery: ["legato", "rhythmic", "dynamic", "precise"],
    personality: ["polished", "playful"],
  },
  {
    id: "elvis-presley", name: "Elvis Presley", type: "Baritone",
    low: "G2", high: "B4", tone: "warm", genres: ["Rock", "Country", "Gospel"],
    blurb: "The King — a rich baritone with rock'n'roll energy and gospel soul.",
    songs: ["Can't Help Falling in Love", "Suspicious Minds", "Jailhouse Rock", "Love Me Tender", "Burning Love"],
    voice: { brightness: 50, warmth: 70, weight: 65, breathiness: 20, roughness: 30, vibrato: 65 },
    technique: ["vibrato", "slides", "scoops", "belt"],
    delivery: ["dramatic", "rhythmic", "elastic", "sustained"],
    personality: ["theatrical", "sensual"],
  },
  {
    id: "david-bowie", name: "David Bowie", type: "Baritone",
    low: "G2", high: "G4", tone: "warm", genres: ["Rock", "Pop"],
    blurb: "Chameleonic baritone — dramatic, characterful and endlessly inventive.",
    songs: ["Heroes", "Life on Mars?", "Space Oddity", "Starman", "Let's Dance"],
    voice: { brightness: 55, warmth: 55, weight: 55, breathiness: 20, roughness: 35, vibrato: 70 },
    technique: ["vibrato", "belt", "slides"],
    delivery: ["dramatic", "elastic", "precise", "sustained"],
    personality: ["theatrical", "inventive"],
  },
  {
    id: "hozier", name: "Hozier", type: "Baritone",
    low: "A2", high: "A4", tone: "dark", genres: ["Rock", "Soul", "Folk"],
    blurb: "Bluesy baritone with gospel weight and a haunting falsetto.",
    songs: ["Take Me to Church", "Cherry Wine", "Work Song", "Too Sweet", "Someone New"],
    voice: { brightness: 35, warmth: 70, weight: 65, breathiness: 30, roughness: 40, vibrato: 55 },
    technique: ["falsetto", "vibrato", "rasp", "belt"],
    delivery: ["dramatic", "sustained", "legato", "dynamic"],
    personality: ["earthy", "soulful"],
  },
  {
    id: "lewis-capaldi", name: "Lewis Capaldi", type: "Tenor",
    low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Soul"],
    blurb: "Gravelly, emotional tenor made for heart-on-sleeve ballads.",
    songs: ["Someone You Loved", "Before You Go", "Bruises", "Wish You the Best", "Hold Me While You Wait"],
    voice: { brightness: 50, warmth: 60, weight: 55, breathiness: 25, roughness: 60, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["dramatic", "sustained", "dynamic", "legato"],
    personality: ["raw", "vulnerable"],
  },
  {
    id: "billie-eilish", name: "Billie Eilish", type: "Mezzo-soprano",
    low: "G3", high: "B4", tone: "dark", genres: ["Pop", "Alternative"],
    blurb: "Soft-spoken, breathy mezzo — understated, moody and intimate.",
    songs: ["Ocean Eyes", "Lovely", "What Was I Made For?", "Birds of a Feather", "Happier Than Ever"],
    voice: { brightness: 30, warmth: 55, weight: 20, breathiness: 75, roughness: 10, vibrato: 15 },
    technique: ["breathy", "soft onset", "straight tone", "vocal fry"],
    delivery: ["intimate", "behind-beat", "understated", "legato"],
    personality: ["intimate", "restrained"],
  },
  {
    id: "lana-del-rey", name: "Lana Del Rey", type: "Mezzo-soprano",
    low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Alternative"],
    blurb: "Cinematic, melancholic mezzo with a vintage haze.",
    songs: ["Video Games", "Summertime Sadness", "Young and Beautiful", "Born to Die", "Say Yes to Heaven"],
    voice: { brightness: 30, warmth: 70, weight: 35, breathiness: 60, roughness: 15, vibrato: 35 },
    technique: ["breathy", "soft onset", "vibrato", "slides"],
    delivery: ["behind-beat", "legato", "understated", "sustained"],
    personality: ["dreamy", "melancholic"],
  },
  {
    id: "taylor-swift", name: "Taylor Swift", type: "Mezzo-soprano",
    low: "G3", high: "D5", tone: "warm", genres: ["Pop", "Country", "Folk"],
    blurb: "Conversational, melodic voice built around storytelling.",
    songs: ["Love Story", "Blank Space", "Anti-Hero", "Cruel Summer", "Fortnight"],
    voice: { brightness: 55, warmth: 55, weight: 35, breathiness: 40, roughness: 10, vibrato: 30 },
    technique: ["straight tone", "breathy", "soft onset", "slides"],
    delivery: ["conversational", "rhythmic", "controlled", "precise"],
    personality: ["conversational", "polished"],
  },
  {
    id: "sia", name: "Sia", type: "Mezzo-soprano",
    low: "A3", high: "E5", tone: "bright", genres: ["Pop"],
    blurb: "Explosive, raspy belter with huge, cathartic choruses.",
    songs: ["Chandelier", "Elastic Heart", "Cheap Thrills", "Titanium", "Unstoppable"],
    voice: { brightness: 70, warmth: 45, weight: 65, breathiness: 20, roughness: 70, vibrato: 60 },
    technique: ["belt", "rasp", "vibrato", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "elastic"],
    personality: ["raw", "commanding"],
  },
  {
    id: "celine-dion", name: "Céline Dion", type: "Soprano",
    low: "B2", high: "C6", tone: "bright", genres: ["Pop"],
    blurb: "Powerhouse balladeer — enormous range, precision and drama.",
    songs: ["My Heart Will Go On", "The Power of Love", "It's All Coming Back to Me Now", "Because You Loved Me", "I'm Alive"],
    voice: { brightness: 70, warmth: 55, weight: 70, breathiness: 10, roughness: 10, vibrato: 85 },
    technique: ["belt", "vibrato", "slides", "runs"],
    delivery: ["dramatic", "powerful", "sustained", "precise"],
    personality: ["polished", "theatrical"],
  },
  {
    id: "mariah-carey", name: "Mariah Carey", type: "Soprano",
    low: "F3", high: "G6", tone: "bright", genres: ["Pop", "R&B"],
    blurb: "Five-octave icon — melismatic runs and a signature whistle register.",
    songs: ["Hero", "We Belong Together", "Always Be My Baby", "All I Want for Christmas Is You", "Fantasy"],
    voice: { brightness: 70, warmth: 55, weight: 50, breathiness: 30, roughness: 10, vibrato: 70 },
    technique: ["runs", "falsetto", "vibrato", "breathy"],
    delivery: ["precise", "dynamic", "elastic", "sustained"],
    personality: ["crystalline", "virtuosic"],
  },
  {
    id: "john-legend", name: "John Legend", type: "Tenor",
    low: "C3", high: "A4", tone: "warm", genres: ["R&B", "Soul", "Pop"],
    blurb: "Smooth soul tenor — piano-led, romantic and refined.",
    songs: ["All of Me", "Ordinary People", "Tonight (Best You Ever Had)", "Nervous", "Green Light"],
    voice: { brightness: 50, warmth: 75, weight: 55, breathiness: 25, roughness: 20, vibrato: 65 },
    technique: ["vibrato", "runs", "belt", "slides"],
    delivery: ["legato", "intimate", "controlled", "rhythmic"],
    personality: ["smooth", "soulful"],
  },
  {
    id: "stevie-wonder", name: "Stevie Wonder", type: "Tenor",
    low: "C3", high: "C5", tone: "bright", genres: ["Soul", "Funk", "R&B"],
    blurb: "Joyful, elastic tenor with impeccable groove and melodic invention.",
    songs: ["Isn't She Lovely", "Superstition", "Signed, Sealed, Delivered", "I Just Called to Say I Love You", "Sir Duke"],
    voice: { brightness: 65, warmth: 65, weight: 50, breathiness: 15, roughness: 25, vibrato: 70 },
    technique: ["runs", "vibrato", "belt", "scoops"],
    delivery: ["rhythmic", "elastic", "dynamic", "precise"],
    personality: ["playful", "soulful"],
  },
  {
    id: "leonard-cohen", name: "Leonard Cohen", type: "Bass-baritone",
    low: "D2", high: "C4", tone: "dark", genres: ["Folk", "Rock"],
    blurb: "Gravelly, poetic low voice — half sung, half spoken, all gravitas.",
    songs: ["Hallelujah", "Suzanne", "Dance Me to the End of Love", "Famous Blue Raincoat", "You Want It Darker"],
    voice: { brightness: 15, warmth: 65, weight: 85, breathiness: 35, roughness: 60, vibrato: 10 },
    technique: ["straight tone", "vocal fry", "firm onset"],
    delivery: ["conversational", "restrained", "behind-beat", "understated"],
    personality: ["earthy", "restrained"],
  },
  {
    id: "toni-braxton", name: "Toni Braxton", type: "Contralto",
    low: "C3", high: "C5", tone: "dark", genres: ["R&B", "Pop"],
    blurb: "Sultry, velvety contralto — one of R&B's richest low voices.",
    songs: ["Un-Break My Heart", "Breathe Again", "He Wasn't Man Enough", "You're Makin' Me High", "Another Sad Love Song"],
    voice: { brightness: 30, warmth: 80, weight: 70, breathiness: 35, roughness: 25, vibrato: 60 },
    technique: ["vibrato", "runs", "slides", "breathy"],
    delivery: ["legato", "sustained", "intimate", "dramatic"],
    personality: ["sensual", "smoky"],
  },
  {
    id: "shawn-mendes", name: "Shawn Mendes", type: "Tenor",
    low: "B2", high: "B4", tone: "warm", genres: ["Pop"],
    blurb: "Bright pop tenor with an easy falsetto and guitar-driven hooks.",
    songs: ["Stitches", "Mercy", "There's Nothing Holdin' Me Back", "Se\u00f1orita", "In My Blood"],
    voice: { brightness: 65, warmth: 55, weight: 35, breathiness: 35, roughness: 15, vibrato: 40 },
    technique: ["falsetto", "breathy", "soft onset", "runs"],
    delivery: ["rhythmic", "conversational", "controlled", "legato"],
    personality: ["polished", "earnest"],
  },
  {
    id: "dua-lipa", name: "Dua Lipa", type: "Mezzo-soprano",
    low: "F3", high: "B4", tone: "dark", genres: ["Pop", "Dance"],
    blurb: "Cool, low-slung mezzo made for disco-pop grooves.",
    songs: ["Levitating", "Don't Start Now", "New Rules", "Houdini", "Training Season"],
    voice: { brightness: 35, warmth: 60, weight: 45, breathiness: 30, roughness: 15, vibrato: 20 },
    technique: ["straight tone", "firm onset", "vocal fry"],
    delivery: ["rhythmic", "controlled", "precise", "understated"],
    personality: ["cool", "restrained"],
  },
  {
    id: "rihanna", name: "Rihanna", type: "Alto",
    low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Dance"],
    blurb: "Distinctive, edgy alto with instantly memorable hooks.",
    songs: ["Diamonds", "Stay", "Umbrella", "Lift Me Up", "Love on the Brain"],
    voice: { brightness: 55, warmth: 55, weight: 50, breathiness: 30, roughness: 30, vibrato: 35 },
    technique: ["straight tone", "slides", "rasp", "belt"],
    delivery: ["rhythmic", "precise", "controlled", "conversational"],
    personality: ["cool", "edgy"],
  },
  {
    id: "chris-stapleton", name: "Chris Stapleton", type: "Tenor",
    low: "A2", high: "B4", tone: "dark", genres: ["Country", "Rock", "Blues"],
    blurb: "Whiskey-soaked country tenor with serious blues power.",
    songs: ["Tennessee Whiskey", "Broken Halos", "Starting Over", "White Horse", "Think I'm in Love with You"],
    voice: { brightness: 40, warmth: 65, weight: 75, breathiness: 15, roughness: 70, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["powerful", "dramatic", "sustained", "elastic"],
    personality: ["raw", "earthy"],
  },
  {
    id: "dolly-parton", name: "Dolly Parton", type: "Soprano",
    low: "G3", high: "D5", tone: "bright", genres: ["Country", "Pop"],
    blurb: "Sparkling country soprano with a quicksilver vibrato.",
    songs: ["Jolene", "9 to 5", "I Will Always Love You", "Here You Come Again", "Coat of Many Colors"],
    voice: { brightness: 80, warmth: 60, weight: 30, breathiness: 20, roughness: 15, vibrato: 85 },
    technique: ["vibrato", "slides", "scoops"],
    delivery: ["conversational", "rhythmic", "precise", "controlled"],
    personality: ["sparkling", "playful"],
  },
  {
    id: "aretha-franklin", name: "Aretha Franklin", type: "Mezzo-soprano",
    low: "F3", high: "E5", tone: "bright", genres: ["Soul", "Gospel", "R&B"],
    blurb: "The Queen of Soul — gospel fire, effortless power and total command.",
    songs: ["Respect", "(You Make Me Feel Like) A Natural Woman", "Think", "I Say a Little Prayer", "Chain of Fools"],
    voice: { brightness: 70, warmth: 65, weight: 70, breathiness: 10, roughness: 35, vibrato: 75 },
    technique: ["belt", "runs", "vibrato", "scoops"],
    delivery: ["powerful", "dynamic", "elastic", "dramatic"],
    personality: ["commanding", "soulful"],
  },
  {
    id: "thom-yorke", name: "Thom Yorke", type: "Tenor",
    low: "B2", high: "A4", tone: "bright", genres: ["Alternative", "Rock"],
    blurb: "Ethereal alt-rock tenor — a soaring falsetto and elastic, expressive phrasing.",
    songs: ["Creep", "Karma Police", "Fake Plastic Trees", "No Surprises", "Everything in Its Right Place"],
    voice: { brightness: 65, warmth: 40, weight: 30, breathiness: 40, roughness: 20, vibrato: 60 },
    technique: ["falsetto", "vibrato", "slides", "soft onset"],
    delivery: ["elastic", "dramatic", "legato", "sustained"],
    personality: ["ethereal", "vulnerable"],
  },
  {
    id: "olivia-rodrigo", name: "Olivia Rodrigo", type: "Mezzo-soprano",
    low: "G3", high: "D5", tone: "warm", genres: ["Pop", "Alternative", "Rock"],
    blurb: "Diary-honest pop-rock voice — conversational verses that break into cathartic choruses.",
    songs: ["drivers license", "good 4 u", "vampire", "deja vu", "traitor"],
    voice: { brightness: 55, warmth: 55, weight: 40, breathiness: 45, roughness: 20, vibrato: 35 },
    technique: ["breathy", "soft onset", "belt", "straight tone"],
    delivery: ["conversational", "dynamic", "dramatic", "intimate"],
    personality: ["honest", "vulnerable"],
  },
  {
    id: "sabrina-carpenter", name: "Sabrina Carpenter", type: "Soprano",
    low: "A3", high: "E5", tone: "bright", genres: ["Pop"],
    blurb: "Playful, bright pop soprano with a sweet head voice and cheeky, precise phrasing.",
    songs: ["Espresso", "Please Please Please", "Taste", "Nonsense", "Manchild"],
    voice: { brightness: 70, warmth: 55, weight: 30, breathiness: 35, roughness: 10, vibrato: 45 },
    technique: ["runs", "falsetto", "vibrato", "soft onset"],
    delivery: ["rhythmic", "precise", "controlled", "conversational"],
    personality: ["playful", "sparkling"],
  },
  {
    id: "chappell-roan", name: "Chappell Roan", type: "Soprano",
    low: "G3", high: "E5", tone: "bright", genres: ["Pop", "Dance"],
    blurb: "Theatrical camp-pop soprano — huge belts and a soaring, elastic top.",
    songs: ["Good Luck, Babe!", "Pink Pony Club", "HOT TO GO!", "Red Wine Supernova", "The Giver"],
    voice: { brightness: 70, warmth: 50, weight: 55, breathiness: 20, roughness: 15, vibrato: 60 },
    technique: ["belt", "vibrato", "falsetto", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "elastic"],
    personality: ["theatrical", "bold"],
  },
  {
    id: "harry-styles", name: "Harry Styles", type: "Tenor",
    low: "B2", high: "B4", tone: "warm", genres: ["Pop", "Rock"],
    blurb: "Warm, easygoing tenor with a rock edge and a relaxed, breezy delivery.",
    songs: ["As It Was", "Watermelon Sugar", "Adore You", "Sign of the Times", "Late Night Talking"],
    voice: { brightness: 50, warmth: 65, weight: 50, breathiness: 30, roughness: 30, vibrato: 45 },
    technique: ["belt", "vibrato", "slides", "falsetto"],
    delivery: ["legato", "rhythmic", "controlled", "dramatic"],
    personality: ["charming", "relaxed"],
  },
  {
    id: "the-weeknd", name: "The Weeknd", type: "Tenor",
    low: "C3", high: "C5", tone: "bright", genres: ["R&B", "Pop"],
    blurb: "Silky, airy high tenor — 80s-tinged falsetto and cinematic hooks.",
    songs: ["Blinding Lights", "Die for You", "Save Your Tears", "Starboy", "Timeless"],
    voice: { brightness: 65, warmth: 55, weight: 30, breathiness: 50, roughness: 10, vibrato: 55 },
    technique: ["falsetto", "vibrato", "breathy", "runs"],
    delivery: ["legato", "sustained", "dramatic", "precise"],
    personality: ["dreamy", "cinematic"],
  },
  {
    id: "sza", name: "SZA", type: "Alto",
    low: "F3", high: "C5", tone: "warm", genres: ["R&B", "Pop"],
    blurb: "Conversational, elastic alto — jazzy melodies and effortlessly off-kilter phrasing.",
    songs: ["Kill Bill", "Snooze", "Good Days", "Saturn", "Nobody Gets Me"],
    voice: { brightness: 45, warmth: 70, weight: 40, breathiness: 50, roughness: 15, vibrato: 30 },
    technique: ["breathy", "runs", "slides", "soft onset"],
    delivery: ["conversational", "behind-beat", "elastic", "intimate"],
    personality: ["dreamy", "candid"],
  },
  {
    id: "doja-cat", name: "Doja Cat", type: "Alto",
    low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Hip-Hop"],
    blurb: "Chameleonic voice — sweet melodic hooks one bar, rap swagger the next.",
    songs: ["Say So", "Kiss Me More", "Paint the Town Red", "Woman", "Agora Hills"],
    voice: { brightness: 55, warmth: 60, weight: 40, breathiness: 35, roughness: 20, vibrato: 30 },
    technique: ["straight tone", "breathy", "runs", "slides"],
    delivery: ["rhythmic", "conversational", "precise", "controlled"],
    personality: ["playful", "versatile"],
  },
  {
    id: "miley-cyrus", name: "Miley Cyrus", type: "Alto",
    low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Rock"],
    blurb: "Husky, smoky alto with rock grit and a big, gutsy belt.",
    songs: ["Flowers", "Wrecking Ball", "Midnight Sky", "Angels Like You", "Used to Be Young"],
    voice: { brightness: 40, warmth: 60, weight: 65, breathiness: 25, roughness: 60, vibrato: 55 },
    technique: ["rasp", "belt", "vibrato", "slides"],
    delivery: ["powerful", "dramatic", "dynamic", "conversational"],
    personality: ["raw", "gutsy"],
  },
  {
    id: "benson-boone", name: "Benson Boone", type: "Tenor",
    low: "C3", high: "C5", tone: "bright", genres: ["Pop", "Rock"],
    blurb: "Powerhouse pop tenor — huge belts, soaring falsetto and theatrical drama.",
    songs: ["Beautiful Things", "Slow It Down", "Mystical Magical", "In the Stars", "Sorry I'm Here for Someone Else"],
    voice: { brightness: 65, warmth: 55, weight: 55, breathiness: 20, roughness: 25, vibrato: 65 },
    technique: ["belt", "falsetto", "vibrato", "slides"],
    delivery: ["dramatic", "powerful", "dynamic", "sustained"],
    personality: ["theatrical", "earnest"],
  },
  {
    id: "teddy-swims", name: "Teddy Swims", type: "Tenor",
    low: "A2", high: "B4", tone: "dark", genres: ["Soul", "Pop", "R&B"],
    blurb: "Gravel-and-honey soul tenor — raspy, warm and enormously emotive.",
    songs: ["Lose Control", "The Door", "Bad Dreams", "Some Things I'll Never Know", "Guilty"],
    voice: { brightness: 40, warmth: 75, weight: 70, breathiness: 20, roughness: 70, vibrato: 60 },
    technique: ["rasp", "belt", "vibrato", "runs"],
    delivery: ["powerful", "dramatic", "sustained", "legato"],
    personality: ["soulful", "raw"],
  },
  {
    id: "noah-kahan", name: "Noah Kahan", type: "Tenor",
    low: "B2", high: "A4", tone: "warm", genres: ["Folk", "Pop"],
    blurb: "Earnest folk-pop tenor — gravelly edges, stomping choruses and storytelling verses.",
    songs: ["Stick Season", "Dial Drunk", "Northern Attitude", "She Calls Me Back", "Everywhere, Everything"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 30, roughness: 45, vibrato: 35 },
    technique: ["rasp", "straight tone", "belt", "slides"],
    delivery: ["conversational", "dynamic", "rhythmic", "dramatic"],
    personality: ["earnest", "earthy"],
  },
  {
    id: "post-malone", name: "Post Malone", type: "Baritone",
    low: "G2", high: "G4", tone: "warm", genres: ["Pop", "Hip-Hop", "Country"],
    blurb: "Laid-back baritone with a sad-eyed croon and a surprising country warmth.",
    songs: ["Circles", "Sunflower", "I Had Some Help", "Better Now", "Chemical"],
    voice: { brightness: 45, warmth: 65, weight: 55, breathiness: 35, roughness: 35, vibrato: 50 },
    technique: ["vibrato", "slides", "breathy", "straight tone"],
    delivery: ["behind-beat", "conversational", "legato", "understated"],
    personality: ["melancholic", "laid-back"],
  },
  {
    id: "gracie-abrams", name: "Gracie Abrams", type: "Soprano",
    low: "G3", high: "C5", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Hushed, breathy whisper-pop — diaristic and close to the mic.",
    songs: ["I Love You, I'm Sorry", "That's So True", "Risk", "Close to You", "Feels Like"],
    voice: { brightness: 50, warmth: 55, weight: 20, breathiness: 75, roughness: 10, vibrato: 15 },
    technique: ["breathy", "soft onset", "straight tone", "vocal fry"],
    delivery: ["intimate", "conversational", "understated", "legato"],
    personality: ["intimate", "confessional"],
  },
  {
    id: "tate-mcrae", name: "Tate McRae", type: "Mezzo-soprano",
    low: "G3", high: "C5", tone: "warm", genres: ["Pop", "Dance"],
    blurb: "Cool, breathy dance-pop mezzo with a conversational, rhythmic edge.",
    songs: ["Greedy", "Exes", "You Broke Me First", "Sports Car", "Revolving Door"],
    voice: { brightness: 50, warmth: 50, weight: 30, breathiness: 60, roughness: 15, vibrato: 20 },
    technique: ["breathy", "straight tone", "soft onset", "vocal fry"],
    delivery: ["rhythmic", "understated", "controlled", "precise"],
    personality: ["cool", "sleek"],
  },
  {
    id: "lady-gaga", name: "Lady Gaga", type: "Mezzo-soprano",
    low: "F3", high: "E5", tone: "bright", genres: ["Pop", "Dance", "Jazz"],
    blurb: "Theatrical powerhouse — brassy belts, jazz phrasing and total vocal control.",
    songs: ["Shallow", "Die with a Smile", "Abracadabra", "Bad Romance", "Always Remember Us This Way"],
    voice: { brightness: 65, warmth: 60, weight: 70, breathiness: 15, roughness: 30, vibrato: 75 },
    technique: ["belt", "vibrato", "slides", "runs"],
    delivery: ["dramatic", "powerful", "dynamic", "precise"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "rose", name: "ROSÉ", type: "Soprano",
    low: "A3", high: "E5", tone: "bright", genres: ["Pop", "K-Pop"],
    blurb: "Distinctive, plaintive soprano with an airy, bittersweet top.",
    songs: ["APT.", "Toxic Till the End", "On the Ground", "Number One Girl", "Gone"],
    voice: { brightness: 75, warmth: 45, weight: 25, breathiness: 45, roughness: 10, vibrato: 40 },
    technique: ["breathy", "vibrato", "soft onset", "straight tone"],
    delivery: ["legato", "sustained", "controlled", "intimate"],
    personality: ["wistful", "distinctive"],
  },
  {
    id: "tyla", name: "Tyla", type: "Alto",
    low: "G3", high: "C5", tone: "warm", genres: ["Pop", "R&B", "Afropop"],
    blurb: "Silky, sultry amapiano-pop alto — smooth, breathy and rhythmically playful.",
    songs: ["Water", "Push 2 Start", "Jump", "Truth or Dare", "Art"],
    voice: { brightness: 50, warmth: 65, weight: 35, breathiness: 55, roughness: 10, vibrato: 20 },
    technique: ["breathy", "soft onset", "straight tone", "runs"],
    delivery: ["rhythmic", "intimate", "controlled", "understated"],
    personality: ["sultry", "smooth"],
  },
  {
    id: "justin-bieber", name: "Justin Bieber", type: "Tenor",
    low: "C3", high: "B4", tone: "warm", genres: ["Pop", "R&B"],
    blurb: "Light, agile pop-R&B tenor with a silky falsetto and easy runs.",
    songs: ["Peaches", "Ghost", "Love Yourself", "Daisies", "Yukon"],
    voice: { brightness: 60, warmth: 60, weight: 35, breathiness: 40, roughness: 10, vibrato: 40 },
    technique: ["falsetto", "runs", "breathy", "soft onset"],
    delivery: ["rhythmic", "legato", "controlled", "intimate"],
    personality: ["smooth", "polished"],
  },
  {
    id: "zach-bryan", name: "Zach Bryan", type: "Baritone",
    low: "A2", high: "A4", tone: "warm", genres: ["Country", "Folk"],
    blurb: "Ragged, heartfelt country-folk voice — cracked edges and raw sincerity.",
    songs: ["Something in the Orange", "I Remember Everything", "Pink Skies", "Heading South", "28"],
    voice: { brightness: 45, warmth: 60, weight: 55, breathiness: 30, roughness: 55, vibrato: 25 },
    technique: ["rasp", "straight tone", "firm onset", "slides"],
    delivery: ["conversational", "dramatic", "dynamic", "restrained"],
    personality: ["raw", "earnest"],
  },
  {
    id: "morgan-wallen", name: "Morgan Wallen", type: "Baritone",
    low: "A2", high: "A4", tone: "warm", genres: ["Country", "Pop"],
    blurb: "Twangy, gravelly country baritone built for radio hooks.",
    songs: ["Last Night", "Whiskey Glasses", "I Had Some Help", "Love Somebody", "Wasted on You"],
    voice: { brightness: 50, warmth: 55, weight: 55, breathiness: 20, roughness: 50, vibrato: 35 },
    technique: ["rasp", "straight tone", "slides", "firm onset"],
    delivery: ["rhythmic", "conversational", "controlled", "precise"],
    personality: ["twangy", "easygoing"],
  },
  {
    id: "alex-warren", name: "Alex Warren", type: "Tenor",
    low: "C3", high: "B4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Anthemic folk-pop tenor — hushed verses that swell into huge, hymn-like choruses.",
    songs: ["Ordinary", "Carry You Home", "Burning Down", "Bloodline", "Eternity"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 35, roughness: 30, vibrato: 50 },
    technique: ["belt", "breathy", "vibrato", "soft onset"],
    delivery: ["dramatic", "dynamic", "sustained", "legato"],
    personality: ["anthemic", "earnest"],
  },
  {
    id: "lola-young", name: "Lola Young", type: "Alto",
    low: "F3", high: "C5", tone: "dark", genres: ["Pop", "Soul", "Alternative"],
    blurb: "Husky, unfiltered London alto — raspy, candid and stylishly messy.",
    songs: ["Messy", "Conceited", "Wish You Were Dead", "One Thing", "Big Brown Eyes"],
    voice: { brightness: 40, warmth: 60, weight: 50, breathiness: 40, roughness: 55, vibrato: 30 },
    technique: ["rasp", "straight tone", "slides", "breathy"],
    delivery: ["conversational", "dynamic", "elastic", "intimate"],
    personality: ["candid", "raw"],
  },
  {
    id: "raye", name: "RAYE", type: "Mezzo-soprano",
    low: "G3", high: "D5", tone: "warm", genres: ["Pop", "R&B", "Jazz"],
    blurb: "Jazz-schooled pop mezzo — theatrical dynamics, big belts and razor diction.",
    songs: ["Escapism.", "Worth It.", "Prada", "Ice Cream Man.", "Genesis."],
    voice: { brightness: 60, warmth: 60, weight: 55, breathiness: 25, roughness: 25, vibrato: 65 },
    technique: ["belt", "runs", "vibrato", "slides"],
    delivery: ["dramatic", "dynamic", "precise", "elastic"],
    personality: ["theatrical", "commanding"],
  },
  {
    id: "olivia-dean", name: "Olivia Dean", type: "Mezzo-soprano",
    low: "G3", high: "C5", tone: "warm", genres: ["Soul", "Pop", "Jazz"],
    blurb: "Sunlit, velvety soul-pop voice — warm, relaxed and effortlessly tuneful.",
    songs: ["Dive", "Man I Need", "Nice to Each Other", "The Hardest Part", "Ladies Room"],
    voice: { brightness: 50, warmth: 80, weight: 45, breathiness: 35, roughness: 10, vibrato: 45 },
    technique: ["vibrato", "soft onset", "runs", "slides"],
    delivery: ["legato", "controlled", "intimate", "rhythmic"],
    personality: ["warm", "easygoing"],
  },
  {
    id: "myles-smith", name: "Myles Smith", type: "Tenor",
    low: "B2", high: "A4", tone: "warm", genres: ["Pop", "Folk"],
    blurb: "Big-hearted stadium-folk tenor with a gritty, joyful edge.",
    songs: ["Stargazing", "Nice to Meet You", "Wait for You", "My First Heartbreak", "Solo"],
    voice: { brightness: 55, warmth: 60, weight: 50, breathiness: 25, roughness: 40, vibrato: 35 },
    technique: ["belt", "rasp", "straight tone", "slides"],
    delivery: ["dynamic", "rhythmic", "dramatic", "conversational"],
    personality: ["joyful", "earnest"],
  },
  {
    id: "bad-bunny", name: "Bad Bunny", type: "Baritone",
    low: "G2", high: "G4", tone: "dark", genres: ["Latin", "Reggaeton", "Pop"],
    blurb: "Low, laid-back Latin baritone — half-sung, half-rapped, effortlessly cool.",
    songs: ["DtMF", "Tití Me Preguntó", "Me Porto Bonito", "Baile Inolvidable", "Dakiti"],
    voice: { brightness: 35, warmth: 55, weight: 60, breathiness: 30, roughness: 30, vibrato: 15 },
    technique: ["straight tone", "vocal fry", "firm onset"],
    delivery: ["rhythmic", "conversational", "understated", "behind-beat"],
    personality: ["cool", "laid-back"],
  },
  {
    id: "shakira", name: "Shakira", type: "Alto",
    low: "F3", high: "C5", tone: "bright", genres: ["Latin", "Pop"],
    blurb: "Unmistakable yodel-tinged alto — husky lows, sudden breaks and bright pop hooks.",
    songs: ["Hips Don't Lie", "Whenever, Wherever", "Soltera", "Waka Waka", "TQG"],
    voice: { brightness: 60, warmth: 55, weight: 45, breathiness: 25, roughness: 45, vibrato: 60 },
    technique: ["vibrato", "rasp", "slides", "scoops"],
    delivery: ["rhythmic", "dynamic", "elastic", "dramatic"],
    personality: ["distinctive", "fiery"],
  },
];

function spotifyUrl(title, artist) {
  return "https://open.spotify.com/search/" + encodeURIComponent(title + " " + artist);
}

function youtubeUrl(title, artist) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(artist + " " + title);
}

function karaokeUrl(title, artist) {
  return "https://www.youtube.com/results?search_query=" + encodeURIComponent(artist + " " + title + " karaoke");
}
